### ISSUE TITLE
Fix trait/perk: Mounted Archer

### ISSUE THREAD

**Issue by johnshepardn7117** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#10]
Same issue as with disciplinarian, So I will list them off here, unless you want me to do a separate link to each?

 If these don't then I assume, many others don't either.

Trait confirmed not to work.

Mounted Archery trait: allowing any bow to be used on horseman.
Mounted Crossbows: allowing reloading on horseback

**Comment by johnshepardn7117** [comment]
Mod claiming to have fixed the issue: (permission needed)

https://www.nexusmods.com/mountandblade2bannerlord/mods/215?tab=files&file_id=842&nmm=1

**Comment by ajseavey** [comment]
I'm the author of that fix and will be looking into incorporating it into this mod tonight.

**Comment by Jayshua83** [comment]
Is this still happening? Would be really nice to not have so many mods! :)

**Comment by ajseavey** [comment]
It is. Working on getting a proper implementation work. Have one last thing to iron out, I think.

**Comment by Velken** [comment]
Cant use Noble Long Bow on horse with Bow Expert nor with Mounted Archer. (e1.1.0-Beta)

**Comment by Jayshua83** [comment]
> Cant use Noble Long Bow on horse with Bow Expert nor with Mounted Archer. (e1.1.0-Beta)

I can with the mod that fixes those perks!
