### ISSUE TITLE
Bannerlord perk still not working

### ISSUE THREAD

**Issue by TheRealBix** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#101]
Bannerlord perk in Steward tree isn't working
Same for the one just below (Logistics Expert ?)

Last version of your mod on e1.0.9

**Comment by Skau** [comment]
This is now fixed. I created a new release that you can download [here](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/tag/0.0.2-hotfix2).
Let us know if there are any other issues!
