### ISSUE TITLE
Consent

### ISSUE THREAD

**Issue by KenRiehle** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#11]
Have you given your consent for your mod to be placed on NexusMods by a person named JackQW?

If so then great glad to hear it if not I reported it that he didn't create the mod and you should do the same. I wasn't going to put your work on a site without permission. BTW the mod works great from what i have tested. Not one issue from upgrading the bandits so far.

Thank you for fixing the issue so quickly from before.

**Comment by Tyler-IN** [comment]
yeah, that's me
