### ISSUE TITLE
How to make a CI/CD workflow for Mod?

### ISSUE THREAD

**Issue by WuZhuoran** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#117]
Hi,

This question is not related to Mod itself. I mean, we write a mod in C# usually. Is there a way to build a CI/CD workflow for our Mod? 

Each time the PR must pass the CI/CD build before it get merged. 

Do you think that will make our life easier? 

For example I saw some examples such as [factorio-mod-luacheck](https://github.com/marketplace/actions/factorio-mod-luacheck), you can view more examples here: https://github.com/marketplace?type=actions&query=mod

Thank you.

**Comment by Tyler-IN** [comment]
We don't have any way to reference TaleWorlds assemblies on a public CI.

We might need to buy a private one or something. I'm not sure. It might not be possible at the moment.
