### ISSUE TITLE
crashing at start up since 1.0.10

### ISSUE THREAD

**Issue by seadoba** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#121]
I disabled all other mods, the problem is in the cmt. patch. all others work normally.

game closes when starting.
![Untitled](https://user-images.githubusercontent.com/63498031/79041602-70d5f580-7bc7-11ea-972e-3ce18b9e7e81.jpg)

**Comment by Tyler-IN** [comment]
By 'start up' you mean before the main menu?

**Comment by seadoba** [comment]
Yeah. Solved with format c: .

Cya!

**Comment by Tyler-IN** [comment]
Oof.
