### ISSUE TITLE
Perk fixes not working on Bannerlord beta 

### ISSUE THREAD

**Issue by liftedtruck** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#125]
Loaded in, noticed issues like not gaining influence and party size from stewardship perks, none of the fixed perks were working, and going into new campaign screen gives log messages like SkippedPatch StewardProminencePatch and so on for all the other perk fixes, disabling other mods doesn't fix the issue either
Using Bannerlord Beta patch 1.1.0 and Community Patch 0.0.2 hotfix 2

**Comment by Tyler-IN** [comment]
Yep, we're looking into generating hashes for methods in a less brittle method to reduce the work needed to update the mod. We gotta slow down to speed up.

There'll be a new release soon.

**Comment by Kamsta99** [comment]
Awesome

**Comment by Tyler-IN** [comment]
Trying to get this sufficiently reviewed before a release.

https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/pull/126
