### ISSUE TITLE
Appraiser/Whole Seller (Tier 1 perk in trading tree) removes the tooltip when comparing weapons/armor/horses

### ISSUE THREAD

**Issue by Violet-Vibes** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#13]
This is a vanilla bug.

Picking either Appraiser or Whole Seller in the trading skill tree removes the highlighting for items in the inventory screen, the ones used to compare whenever or not an item is an upgrade.

![image](https://user-images.githubusercontent.com/19490536/78514532-26f9a380-77b2-11ea-81c4-085d0e1f993e.png) no perks taken

![image](https://user-images.githubusercontent.com/19490536/78514546-409aeb00-77b2-11ea-9a78-b9e65c62e87b.png) notice how the compare now works, the green/red numbers

![image](https://user-images.githubusercontent.com/19490536/78514539-3547bf80-77b2-11ea-8ea1-0997aab83a65.png) either perk taken

![image](https://user-images.githubusercontent.com/19490536/78514567-590b0580-77b2-11ea-99dd-ea19e338c7d0.png) compare is now broken, not showing either green/red numbers.

I'm also pretty sure the perk bonuses emself are not implemented or broken (show profit when trading)

**Comment by Tyler-IN** [comment]
Yeah, I think I saw this when looking at stuff with X-rax... I'll confer with him on it.

The perk check for this functionality is possibly backwards.

**Comment by Tyler-IN** [comment]
After conferring, SPACEDANCE pointed toward ItemMenuVM.GetColorFromComparison.

I'll put together a patch.

**Comment by Violet-Vibes** [comment]
I poked around myself using dnspy but never thought about searching for
comparison... I blame the lack of sleep.


While you're at it, would it be possible to see if the perks are working at
all?

Den mån 6 apr. 2020 03:23Tyler Young <notifications@github.com> skrev:

**Comment by Tyler-IN** [comment]
I pushed a release that includes this fix. Can you give it a test?

I'll look more into the perks themselves too.

**Comment by johnshepardn7117** [comment]
Confirmed, fix.

Question:
What is the proper way to update the files. I had a bit of a headache with the last patch. Simply dropping it on top wasn't working. 
Deleted the entire file, loaded the game launcher, and game. Exited, then proceeded to drop the new file. Then it worked.

**Comment by Violet-Vibes** [comment]
> I pushed a release that includes this fix. Can you give it a test?
> 
> I'll look more into the perks themselves too.

Seems like the fix does indeed work, but it also breaks the comparing when you *dont* have the either perk.

Ie

Have perk = comparing now works, as opposed to pre-fix
Not having perk = comparing now does *not* work, as opposed to pre-fix

**Comment by Violet-Vibes** [comment]
Fixed in latest version of community patch.
