### ISSUE TITLE
Copyright Infringment

### ISSUE THREAD

**Issue by gallexme** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#131]
From Version  0.0.2-hotfix2 to  0.0.2-hotfix3
@Skau 
Do not include Librarys owned by Taleworlds 

TaleWorlds.MountAndBlade.View.dll
TaleWorlds.MountAndBlade.GauntletUI.dll

ill be taking the mod down on mod.io until that issue is fixed, and please remove it from github before taleworlds sends a dcma notice

**Comment by Skau** [comment]
Fixed. Thanks for letting me know.
