### ISSUE TITLE
Tell user that early story quests will fail after 10 years

### ISSUE THREAD

**Issue by iPherian** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#133]
Suggestion is to include somewhere in the UI telling the user that the first phase story line quests (everything up to and including Create / Support Kingdom) will fail after 10 years (which I guess in bannerlord time is 840 days ish). Judging by many posts on taleworlds forums and reddit people are getting blindsided by this.

P.S. Still true after patch 1.0.11, if anyone's wondering.

**Comment by Tyler-IN** [comment]
Good idea.

**Comment by worldsprayer** [comment]
This issue has been removed by TW, you can no longer fail for waiting 10 years.

**Comment by iPherian** [comment]
@worldsprayer From the patch notes for 1.0.11:

> Fixed the bug that caused main storyline quests in _**later**_ stages to terminate after 10 years.

(emphasis mine)

Early stage quests still fail after 10 years, but the game doesn't tell the user anywhere. Early stage means Neretze's folly through Dragon Banner through to Create / Support Kingdom. Referred to in the game code as "First Phase" quests.

This is just stable version. If they fixed it in beta.....well i'll feel like an idiot. :sweat_smile:

(but I don't see it in beta patch notes)

<details>
<summary>To demonstrate, the game's code (stable 1.0.11)  (don't read if you don't care)</summary>

###

See the function (in dotPeek perhaps) StoryMode.Behaviors.FirstPhaseCampaignBehavior.WeeklyTick for details. It's in "(bannerlord install dir)\Modules\StoryMode\bin\Win64_Shipping_Client\StoryMode.dll"

Here's it in latest patch (1.0.11) with some small redactions for clarity:

```
private void WeeklyTick()
{
  if (FirstPhase.Instance == null ||
	  SecondPhase.Instance != null ||
	  FirstPhase.Instance.FirstPhaseStartTime.ElapsedYearsUntilNow <= 10.0)
	return;

  // fail all active story line quests
}
```

As you can see, it stops failing quests if `SecondPhase.Instance != null`. This means if the second phase of story has been started. Second phase starts with Unify the Empire (called AssembleEmpire in the code) or Weaken the Empire. Anything before that is FirstPhase and that's where the 10 year timeout still happens.

Sorry for the giant post. :wink:
</details>

**Comment by Skau** [comment]
So is it supposed to fail after 10 years (aka we patch it to remove the check), or should we just add UI updates? Personally I find it weird that it is possible to brick your save by failing the main story line by playing at your own pace, but if that's the TW's intention, we will stick by it on this mod.

**Comment by iPherian** [comment]
I don't like it either, but I think it's TW's intention is to keep the timeout. They specifically patched the timeout function in 1.0.11 to add the check for Second Phase starting. So a dev had to look right at the timeout code and he could have removed the entire thing but he didn't, just restricted it to First Phase. I very much think the user should be warned, though.

If people are interested, I might have heard of another mod which does remove the timeout.....possibly.....maybe.......once upon a time......

https://github.com/iPherian/Bannerlord_No_Dragon_Banner_Timeout
https://www.nexusmods.com/mountandblade2bannerlord/mods/370

[/shameless_plug]

Yeah I wrote that one :wink:

**Comment by worldsprayer** [comment]
TW in the patch notes on the beta .11 said it was a bug that it timed out.
"Fixed the bug that caused main storyline quests in later stages to terminate after 10 years."
That's what I get from it.

**Comment by worldsprayer** [comment]
oh didnt see all those above. i have to admit, what counts as later?  to me it sounds like none are meant to fail after ten years, they have repeastedly stated the main quest was optional.  Time limits makes it not so optional.

**Comment by Skau** [comment]
Later in this case means phase 2 and 3 of the main storyline quest. Phase 1 (the one that still has the 10 year termination) is up until you create a kingdom/give the dragon banner to someone.

**Comment by iPherian** [comment]
@worldsprayer Also the code changes reveal their intent very precisely, I think.

This is pre 1.0.11 patch:

```
private void WeeklyTick()
{
  if (FirstPhase.Instance == null ||
	  FirstPhase.Instance.FirstPhaseStartTime.ElapsedYearsUntilNow <= 10.0)
	return;

  // fail all active story line quests
}
```

post patch:

```
private void WeeklyTick()
{
  if (FirstPhase.Instance == null ||
	  SecondPhase.Instance != null ||
	  FirstPhase.Instance.FirstPhaseStartTime.ElapsedYearsUntilNow <= 10.0)
	return;

  // fail all active story line quests
}
```

I can't make a diff in here but you can see the only difference is that it stops timing out quests when SecondPhase starts. See other comments for what the phases are.

**Comment by iPherian** [comment]
> oh didnt see all those above. i have to admit, what counts as later? to me it sounds like none are meant to fail after ten years, they have repeastedly stated the main quest was optional. Time limits makes it not so optional.

@worldsprayer That being said, if you want to remove the timeout altogether there are mods for that. I use one.
