### ISSUE TITLE
1.1.x: Crash due to NRE in SimulateSingleHit called by SimulateBattleForRound

### ISSUE THREAD

**Issue by ghosteca** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#134]
![Annotation 2020-04-12 151734](https://user-images.githubusercontent.com/60903230/79172596-63c92a00-7db2-11ea-891c-98c23fb539d2.png)

I have mods installed but it seems to happen even with all mods disabled.

**Comment by Tyler-IN** [comment]
We don't patch SimulateBattleForRound or SimulateSingleHit... There could be a bug in there that we need to patch.

**Comment by TYoung86** [comment]
Saw on discord,
![another one](https://cdn.discordapp.com/attachments/333283527363788810/699741843998638231/Capture.JPG)

**Comment by Tyler-IN** [comment]
Not sure if fixed, closing as stale.
