### ISSUE TITLE
Mod Load Order Question...

### ISSUE THREAD

**Issue by Jayshua83** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#136]
Not a Bug per say!

But when using the Fixed Launcher, Community Patch always slides above the TW modules and I move it below them. It should load after them? Correct? To overwrite their broke stuff with fixes?

**Comment by Tyler-IN** [comment]
Community Patch's intended sort order is as high (early) as possible, not later.

It doesn't overwrite anything by replacing files, and other mods should be able to overwrite/replace it's files.
