### ISSUE TITLE
Crash When Loading Custom Battle

### ISSUE THREAD

**Issue by Cheyron** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#147]
This crash happens after you switch your characters from the default options in the custom battle setup screen. If you don't change anything and only tweak the troop values then there will not be a crash. It seems to only happen when you had switched characters and then the load screen will freeze up. Thanks!
Unchecking Community Patch in the launcher and CP alone will allow you to load a custom battle as normal even if you had changed switched characters/heroes.
Try doing Ratagost vs Carfyd, Sturgia vs Battania and any troop values should produce a crash with CP checked.

After a little research the culprit code that could be crashing when loading a custom battle...
```cs
protected static bool HeroHasPerk(BasicCharacterObject character, PerkObject perk) {
  var heroObject = character.IsHero ? (CharacterObject) character : null;
  return heroObject?.GetPerkValue(perk) ?? false;
}
```
The exception...
```
System.InvalidCastException
HResult=0x80004002
Message=Unable to cast object of type 'TaleWorlds.Core.BasicCharacterObject' to type 'TaleWorlds.CampaignSystem.CharacterObject'.
Source=
StackTrace:
```

**Comment by Tyler-IN** [comment]
I troubleshot this issue w/ Cheryon over Discord.

The community patch diagnostic report didn't work here. Need to look into that separately.

**Comment by Cheyron** [comment]
Custom battle is now confirmed working in the test release I was provided over Discord. Thanks for your help!
