### ISSUE TITLE
Man-at-Arms and Bannerlord are calculating extra? - Perks  - Steward

### ISSUE THREAD

**Issue by techxoxo** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#163]
Steward perks Man-at-Arms & Bannerlord, fixed in an earlier patch seems to be calculating the numbers a bit excessive?
As per the Kingdom page the fiefs are castles and cities only while towns are not considered fiefs, but the perk considers them as fiefs as well, is this intentional or just a bug?

Also a minor graphical issue, Base amount appears twice in the list, once at the top, then a sum of above values before the perks, however they dont double count, but it just appears.

game version 1.0.11

![image](https://user-images.githubusercontent.com/63734780/79362435-083c9f00-7f60-11ea-9b28-5c20bba08226.png)

**Comment by Skau** [comment]
Thanks for the info.
