### ISSUE TITLE
IsThirdPartyOption

### ISSUE THREAD

**Issue by Aragas** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#169]
Hello!
In the method [CommunityPatch.IsThirdPartyOption](item) there seems to be an issue with this line. It causes your mod to crash when used with [Bannerlord.MBOptionScreen](https://github.com/Aragas/Bannerlord.MBOptionScreen).
https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/blob/72a66a2fd1bb6128197fd21af46e353babd4edc4/src/CommunityPatch/MenuCleaner.cs#L66
Because ``Bannerlord.MBOptionScreen`` is implementing a [custom ](https://github.com/Aragas/Bannerlord.MBOptionScreen/blob/8d37b52e9b698dca3d23093ef2ec7c2b54a73930/State/DefaultStateProvider.cs#L67)InitialStateOption, it sets the field ``_action`` to null. The class is removed before OnBeforeInitialModuleScreenSetAsRoot, where it's lifetime ends.
As I do not fully understand your implementation of checking the type here, I didn't try to change it myself.

**Comment by bighungryjames** [comment]
Yeah, having the same problem here!
Here's my crash report: https://imgur.com/a/pdKTd9Y
<blockquote class="imgur-embed-pub" lang="en" data-id="a/pdKTd9Y" data-context="false" ><a href="//imgur.com/a/pdKTd9Y"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by buggiant** [comment]
Something wrong with this IsThirdPartyOption crashes my game when start

**Comment by bighungryjames** [comment]
Hmm, I think I need to inform that the Detailed Character Creation mod is composed of two different modules. The !DCC module loads before the native modules, and the DetailedCharacterCreation module loads just like the ordinary module.

**Comment by nyluhem** [comment]
Hey so I have Detailed Character Creation Installed - if you move it after both their modules, it should fix it.

**Comment by bighungryjames** [comment]
> Hey so I have Detailed Character Creation Installed - if you move it after both their modules, it should fix it.

Man you are my lifesaver. Thanks.

**Comment by Tyler-IN** [comment]
This is already fixed in the latest test builds. The previous release had this problem.

The ordering does not matter - but as a side effect, reordering them gets around the problem.

**Comment by Tyler-IN** [comment]
Resolved.
