### ISSUE TITLE
Insurance Plans perk causing hardcap to caravan party size at 30 troops

### ISSUE THREAD

**Issue by Cjorss** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#174]
I just took the Insurance Plans perk and found my active caravans rapidly bleeding troops. It seems that by giving caravans "Elite Units" it means specifically 29 of them and not a one more. With a higher price tag at 18000 Denars my caravan was crushed by steppe bandits within days. And I got my 5000 Denars back, yay... 

Caravans are effectively useless in my game now. 

An example of the elite troops that my extra 3000 Denars and permanent crippling of caravan size to 30:
6 Khuzait Veteran Caravan Guards
15 Khuzait Armed Traders
8 Khuzait Caravan Guards

**Comment by Yenwood** [comment]
Caravans are limited to 30 troops now. Has nothing to do with insurance plans or this mod.

**Comment by Cjorss** [comment]
> 
> 
> Caravans are limited to 30 troops now. Has nothing to do with insurance plans or this mod.

Thanks for the info, the update must have happened right as I took the perk.
