### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by CallyxH** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#176]
Sorry if this question has already been asked.
I downloaded modlib and bannerlordtweek and since that crash

![image](https://user-images.githubusercontent.com/63864808/79585481-26c1a800-80d0-11ea-8bb1-4650565c8310.png)

**Comment by Tyler-IN** [comment]
Should be fixed in the upcoming release.

**Comment by Tyler-IN** [comment]
Duplicates #169
