### ISSUE TITLE
Improve (remove?) Harmony facade (and/or provide better examples)

### ISSUE THREAD

**Issue by DoctorVanGogh** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#188]
The whole `IPatch`/`PatchBase` infrastructure (or possibly it's lack of examples) feel like a very limited facade over Harmony.

Most (all?) current patches make exclusive use of the [`Harmony.Patch`](https://harmony.pardeike.net/api/HarmonyLib.Harmony.html#HarmonyLib_Harmony_Patch_System_Reflection_MethodBase_HarmonyLib_HarmonyMethod_HarmonyLib_HarmonyMethod_HarmonyLib_HarmonyMethod_HarmonyLib_HarmonyMethod_) method to apply changes.

There's an entire additional surface to the Harmony API that is ignored by this:

- [`[HarmonyPriority]`](https://harmony.pardeike.net/api/HarmonyLib.HarmonyPriority.html) - you can set where in the order of multiple patches per method a patch is to be applied
- [`[HarmonyBefore]`](https://harmony.pardeike.net/api/HarmonyLib.HarmonyBefore.html)/[`[HarmonyAfter]`](https://harmony.pardeike.net/api/HarmonyLib.HarmonyAfter.html)/ - you explicitly set which patches to apply before or after a certain patch.
- The entire attributed syntax for patching via [`[HarmonyPatch]`](https://harmony.pardeike.net/api/HarmonyLib.HarmonyPatch.html) - you don't have to do method lookups yourself

Example:

```cs
  public sealed class MaxFoodVarietyPartyMoralePatch : PatchBase<MaxFoodVarietyPartyMoralePatch> {

    public override bool Applied { get; protected set; }

    [HarmonyPatch]
    public static class Patches {
        private static Lazy<MethodInfo> lzTarget = new Lazy<MethodInfo>(
            () => AccessTools.Method(typeof(DefaultPartyMoraleModel), "CalculateFoodVarietyMoraleBonus"))
        
        [HarmonyTargetMethod]
        public static MethodInfo Target() => lzTarget.Value
        
        [HarmonyPostfix]
        public static void AddExtraMorale(MobileParty party, ref ExplainedNumber result) {
          if (party.ItemRoster.FoodVariety > 10) {
            result.Add(party.ItemRoster.FoodVariety - 4f, GameTexts.FindText("str_food_bonus_morale", (string) null));
          }
        }
    }

    public override IEnumerable<MethodBase> GetMethodsChecked() {
      yield return Patches.Target();
    }

    private static readonly byte[][] Hashes = {
      new byte[] {
        // e1.1.0.224785
        0x7B, 0x08, 0xE2, 0x53, 0x78, 0x94, 0x9A, 0x7A,
        0x5D, 0x36, 0x5F, 0xA4, 0x39, 0xF2, 0xF0, 0xE9,
        0xE5, 0x6E, 0x08, 0x46, 0xD0, 0x30, 0x94, 0x58,
        0x1F, 0xF6, 0x18, 0xBC, 0x19, 0xCC, 0x0C, 0xAB
      }
    };

    public override void Reset() {
    }

    public override bool? IsApplicable(Game game)
      // ReSharper disable once CompareOfFloatsByEqualityOperator
    {
      var patchInfo = Harmony.GetPatchInfo(Patches.Target());
      if (AlreadyPatchedByOthers(Patches.Target()))
        return false;

      var hash = Patches.Target().MakeCilSignatureSha256();
      return hash.MatchesAnySha256(Hashes);
    }

    public override void Apply(Game game) {
      if (Applied) return;

      CommunityPatchSubModule.Harmony.CreateClassProcessor(typeof(Patches)).Patch();
      Applied = true;
    }

  }
```
Not inherently better or worse than patching via method call, but allows more explicit and fine grained specification of patches.

**Comment by Tyler-IN** [comment]
`IPatch` and `PatchBase` don't necessarily use Harmony.
They part of establishing a life-cycle and description pattern for the patches.
They are also used to indicate which methods to generate hashes for (e.g. `GetMethodsChecked`).
They will in future have other user preference, static analysis, testing components.

There are patches like the very first patch, for Disciplinarian, that do not use Harmony at all.
There are other attribute-only patches that are applied when PatchAll is invoked, and they are not invoked at the same time as the Patch collection.

I don't know for sure, but I think having a nested class inside of a patch will not avoid the `PatchAll` invocation of the patch.

The use of `AccessTools` instead of `System.Reflection` is user preference.

**Comment by DoctorVanGogh** [comment]
Well yes, if `IPatch` & `PatchBase` have architecture/lifetime functionality then they indeed serve a purpose.
I'd argue then that they are possibly _misnamed_. "Patch" as a concept is already in use for actual IL patches via Harmony. And if the purpose of the interface & class is to do something more than patching (or even not anything to any actual patching at all), then maybe call things "Change"/"Functionality"/"Modification"/"Feature" ? 
Again, of those "Modification" is already blocked by the concept of the whole "Mod". "Change" seems very bland... I think "Functionality" is equally non-descript. Which leaves "Feature"...
Ultimately the name could be anything, but I think the double use of the same term for multiple concepts is confusing in the design.

---

I just checked again, and both on the direct `Harmony.Patch` overloads and via the indirect `Harmony.CreatePatchProcessor` there are no options to specify patch priorities (see https://harmony.pardeike.net/articles/priorities.html ). I understand that "playing nice with others" is not currently too high on your priority list, but there may be actual "sub-patches" where multiple harmony patches are to be applied to the same method. And there _may_ come a case where those patches need to happen in a certain order. Specifying _priorities_ is the only way to guarantee orders here.
Furthermore there are additional steps ([Prepare, TargetMethod[s], Cleanup](https://harmony.pardeike.net/articles/patching.html#method-names)) which can be performed via attributed patching.
There is also some semi advanced stuff that can be at least easier to understand via attributed patching (adding auto mapped private class fields into pre/postfixes without them having assanine parameter names).

But **yes** attributed patching will be picked up via (careless) use of `harmony.PatchAll()`. That should at least be `harmony.PatchAll(fooAssembly)` or even `harmony.CreatePatchProcessor(typeof(PatchOwner)).Patch()`.

That would need examples & explanations.

--- 
As for 
> If another mod wishes to apply a patch before we apply a patch, we opt out by default. 

You are aware that you are shipping an IL patching library yourself? It would be *trivial* to create a tiny mod using Harmony which makes all implementations of `PatchBase.IsApplicable` always just return true.

**Comment by Tyler-IN** [comment]
> Well yes, if `IPatch` & `PatchBase` have architecture/lifetime functionality then they indeed serve a purpose.
> I'd argue then that they are possibly _misnamed_. "Patch" as a concept is already in use for actual IL patches via Harmony. And if the purpose of the interface & class is to do something more than patching (or even not anything to any actual patching at all), then maybe call things "Change"/"Functionality"/"Modification"/"Feature" ?

Uhh... splitting hairs here. Sure. I don't know. The mod was originally named Community Patch and had IPatch before introducing Harmony. Chicken and egg, personal preference, all come into play here. If there's a better name that's fine, but I think all of those ("Change"/"Functionality"/"Modification"/"Feature") don't work. I'm open to more suggestions.


> I just checked again, and both on the direct `Harmony.Patch` overloads and via the indirect `Harmony.CreatePatchProcessor` there are no options to specify patch priorities (see https://harmony.pardeike.net/articles/priorities.html ).
> I understand that "playing nice with others" is not currently too high on your priority list, but there may be actual "sub-patches" where multiple harmony patches are to be applied to the same method. And there _may_ come a case where those patches need to happen in a certain order. Specifying _priorities_ is the only way to guarantee orders here.

HarmonyMethod exposes priority as a public member. When manually applying patches, we can change it before passing in the HarmonyMethod to the prefix/postfix/transpiler/finalizer arguments.
See [HarmonyMethod.cs](https://github.com/pardeike/Harmony/blob/master/Harmony/Public/HarmonyMethod.cs).

As far as "playing nice with others," it _is_ high on the priority list.

> Furthermore there are additional steps ([Prepare, TargetMethod[s], Cleanup](https://harmony.pardeike.net/articles/patching.html#method-names)) which can be performed via attributed patching.
> There is also some semi advanced stuff that can be at least easier to understand via attributed patching (adding auto mapped private class fields into pre/postfixes without them having assanine parameter names).

Are you having trouble understanding something in particular, or is everything in general with the 
current approach hard for you to understand? I haven't gotten this feedback from any current developers actively working on the project. To which individual asinine parameter names are you referring to?

> But **yes** attributed patching will be picked up via (careless) use of `harmony.PatchAll()`. That should at least be `harmony.PatchAll(fooAssembly)` or even `harmony.CreatePatchProcessor(typeof(PatchOwner)).Patch()`.
> 
> That would need examples & explanations.
> 
> As for
> 
> > If another mod wishes to apply a patch before we apply a patch, we opt out by default.
> 
> You are aware that you are shipping an IL patching library yourself? It would be _trivial_ to create a tiny mod using Harmony which makes all implementations of `PatchBase.IsApplicable` always just return true.

I'm not sure where you're going with this, but yeah you could do that, or just check out the project and take out the IsApplicable check and make your own build, but why would you do that?

**Comment by Tyler-IN** [comment]
FTR

The IPatch / PatchBase has several intermediate subclasses now, and are part of target method hash generation
