### ISSUE TITLE
Crash when loading from launch 4/19

### ISSUE THREAD

**Issue by wangofjebus** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#191]
![image](https://user-images.githubusercontent.com/63981827/79701295-c27a2200-8250-11ea-84ed-ed3cf8610de8.png)

**Comment by Tyler-IN** [comment]
Duplicates https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/169

**Comment by Astor1977** [comment]
Same issue here.
