### ISSUE TITLE
Mercenary Contract does not expire:

### ISSUE THREAD

**Issue by johnshepardn7117** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#2]
Merc contract does not expire, as such leaving the contract incurs -20 penalty with every lord of the faction. 
Quick work around this, is to provide a +25 relation with the faction for the contract, thus yielding a +5 positive for enlisting as a merc.

**Comment by Tyler-IN** [comment]
Can you give me a screenshot of this? I think I can just fix the expiry.

**Comment by johnshepardn7117** [comment]
[https://steamuserimages-a.akamaihd.net/ugc/1019444160333656577/6B6C1659144EC591DB789E66D7DD57787227ED6E/](url)

Save file that is my testing grounds: Negative penalty for mercenary contract ending, you are forever bound to your lord lol
[https://knightsucfedu39751-my.sharepoint.com/:u:/g/personal/jsanchez112_knights_ucf_edu/EXxCzjGJqu5JqXbI3qp1LvgB97i2Gwz81dryB0UyMHQonA?e=f9q114](url)

**Comment by Tyler-IN** [comment]
According to the dialog definition, it should invoke ApplyByLeaveKingdom...

When you get that reply, does it leave the kingdom but keep the quest? I'll give the save a test sometime today.

**Comment by Tyler-IN** [comment]
There's a mod that "fixes" this up on Nexus Mods, have you tried it?

**Comment by Tyler-IN** [comment]
After talking to you on discord, you reported a different mod ended up fixing it.
https://www.nexusmods.com/mountandblade2bannerlord/mods/49

I reached out by forum post and I'll try to see about collaborating to get these native fixes integrated.

**Comment by Tyler-IN** [comment]
Linking https://github.com/mipen/BannerlordTweaks/issues/9

**Comment by Tyler-IN** [comment]
e1.0.8: Fixed a bug where ending your mercenary contract with a kingdom resulted in a loss of relationship with the lords of the kingdom.

Might be good to release 0.0.2 w/o this fix in, but would still like to get it implemented for backwards compat.

**Comment by Tyler-IN** [comment]
Still no reply on this.

**Comment by Tyler-IN** [comment]
Closing as stale. :(
