### ISSUE TITLE
Game crash upon start campaign

### ISSUE THREAD

**Issue by PaddyVu** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#204]
https://user-images.githubusercontent.com/64102260/79906757-97572480-8442-11ea-98b0-92142e50595e.png
I'm using bannerlord mod launcher and i cant create new campaign,can load only,so to make new campaign i need to use normal launcher then i can use mod launcher to load save game

**Comment by Tyler-IN** [comment]
Can you go into the Mod Options / Community Patch Options and copy a diagnostic report, then paste it in here?

**Comment by PaddyVu** [comment]
> Can you go into the Mod Options / Community Patch Options and copy a diagnostic report, then paste it in here? 
Done

[diagnostic-report.20200421192354605.F610FBFA.txt](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4517728/diagnostic-report.20200421192354605.F610FBFA.txt)
[diagnostic-report.20200421192648991.0BEAFC41.txt](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4517729/diagnostic-report.20200421192648991.0BEAFC41.txt)
[diagnostic-report.20200421192931364.BD5078F0.txt](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4517730/diagnostic-report.20200421192931364.BD5078F0.txt)
[diagnostic-report.20200422165726960.1BEE7085.txt](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4517731/diagnostic-report.20200422165726960.1BEE7085.txt)
[diagnostic-report.20200422165743794.EAC70396.txt](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4517732/diagnostic-report.20200422165743794.EAC70396.txt)

**Comment by PaddyVu** [comment]
> Can you go into the Mod Options / Community Patch Options and copy a diagnostic report, then paste it in here?

Again,i uncheck your mod using fix launcher still crash,this fault from fix launcher,ty

**Comment by iPherian** [comment]
@PaddyVu So it's not caused by us? Perhaps this can be closed?

**Comment by Tyler-IN** [comment]
The top 3 uploads there are actual crash reports during the visual start up when creating a lord during lading a game; it's checking to see if he has a mount, and something in there accidentally tries to dereference null.

Your save game might be corrupted. Try to find me on Discord and I'll see if I can help fix your save.

**Comment by PaddyVu** [comment]
> The top 3 uploads there are actual crash reports during the visual start up when creating a lord during loading a game; it's checking to see if he has a mount, and something in there accidentally tries to dereference null.
> 
> Your save game might be corrupted. Try to find me on Discord and I'll see if I can help fix your save.
> 
> However, it does not appear to be related to having mods - it might be related to _removing a needed mod._ It's not the launcher.
Hi again,i'm just find out what cause it,i deleted entire M&BII and reinstall,now with only your mod,new campaign load fine,next i use bannerlord mod launcher together,it's fine again,so problem is from " Fixed launcher ",i think it modified something in the bin and module that cause crash when start campaign,dont know what it is :D 
![image](https://user-images.githubusercontent.com/64102260/80082857-1ea9b280-857f-11ea-96df-e2f2f47d714a.png)
