### ISSUE TITLE
Resolve dangling commits in master branch

### ISSUE THREAD

**Issue by iPherian** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#206]
Right now it's like this:

![](https://i.imgur.com/xw8BVv8.jpg)

I've seen a few places where people have assumed that the stuff on master is important somehow and needs to be incorporated, like in this [PR](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/pull/201), and they have merged it in potentially causing conflicts. I think people will continue to assume that about master since it's one of git's fundamental branches. 

I suggest that it somehow be indicated that these commits have been resolved. One way would be to merge master into dev as a true merge commit. Yes, it would make for an uglier commit history, and I prefer to rebase, but the alternative is I guess to leave these dangling commits there forever, which may be confusing.

Interestingly, even though there are duplicates on master and dev, the merge completes without conflicts (tried it locally).

**Comment by Tyler-IN** [comment]
I think I'll be rebasing master on dev for release, until we start pushing release branches we probably won't see many merges.

Maybe after this upcoming release we'll start moving to a more git-flow-esque style.

**Comment by Tyler-IN** [comment]
The dangling commits (EarlyStoryVisibleTimeoutPatch) are now on dev, and master is rebased on dev;
![image](https://user-images.githubusercontent.com/33945568/79975882-a8fff280-8469-11ea-8eb1-d6fa518c1144.png)

**Comment by iPherian** [comment]
@Tyler-IN Fair enough.

As long as we're here, would you mind resetting master to get rid of those 2 commits? And just have it equal to where dev is now I guess? Idc if it's left there for the rest of time, it's just that the commits added were already in dev, but have re-added some junk to the *.csproj it looks like.

Perhaps you could reset master to 2 commits ago [929817c](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/commit/929817c6cc7e79dca0b71da2b41a7dc44d15e5ba) ? (Add Feats section and snow detection fix to README)

**Comment by Tyler-IN** [comment]
Check out the PR to sync master first - do we need to discard that?

**Comment by Tyler-IN** [comment]
I think we're good now.
