### ISSUE TITLE
Incompatiblity with MBOptionScreen xml

### ISSUE THREAD

**Issue by zDCVincent** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#210]
I wanted to report an incompatibility issue. This was discovered through "TML Tweak Mod" a smithing mod on the Nexus. I was told that this crash is due to MBOptionScreen. Even when running MBOptionScreen standalone with Community Patch triggers the crash.

**Comment by Tyler-IN** [comment]
Yeah, this is fixed on the dev but a new release hasn't occurred yet.
