### ISSUE TITLE
Champion Perk does not work

### ISSUE THREAD

**Issue by nhoclesnar** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#213]
Champion Perk in Charm skill doesn't work. It's supposed to give 10 influence for winning tournaments but it doesn't do anything.

**Comment by miguelcjalmeida** [comment]
The Perk worked here, it increased my influence by 10. However, what you might be experience, as I have, is the lack of notification. When the tournament is won, no message is displayed showing the influence gain, but it is accounted. 

Could you confirm if you are receiving the influence points please?

**Comment by Tyler-IN** [comment]
Closing as stale.
