### ISSUE TITLE
Green/Red numbers when comparing items are disabled

### ISSUE THREAD

**Issue by AzucarSalado** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#23]
It happens only with this mod installed

NO MOD:
![image](https://user-images.githubusercontent.com/63239138/78557484-2c3a0b00-7811-11ea-8284-6a19a4c91ea3.png)

WITH MOD:
![image](https://user-images.githubusercontent.com/63239138/78558302-a1f2a680-7812-11ea-8968-c4d2c1f1f4cc.png)

Regards

**Comment by johnshepardn7117** [comment]
This was already posted below, there is another topic about this already.

**Comment by ZMemme** [comment]
This is different. The perk got fixed but if you don't have the perk now the comparisons are disabled.

**Comment by TYoung86** [comment]
I guess the comparison colors should always be shown, regardless of the perks' status.
I'll just change it to not check for the perk.

**Comment by Tyler-IN** [comment]
Disciplinarian

**Comment by Tyler-IN** [comment]
Pushed a release to fix it. Let me know if this is how it should be.

**Comment by kuroyushi** [comment]
Heya, latest update bork'd it again.

**Comment by Tyler-IN** [comment]
Re-released, try again?

**Comment by Violet-Vibes** [comment]
> Yeah I'll just remove the perk check. I thought the perk should be required, but it's only for trade info.

According to the perk description, it should "mark profits" when trading with the selected goods depending on perk, whatever that means.

The green/red comparision numbers should *always* be activated, perk or no perk.

**Comment by AlcoholV** [comment]
There is no such cases as basic convenience features added to perk option.
I think the function for the trade profit  went in the wrong. 
If this is intended, I may really disappointed with the dev's game development philosophy.

**Comment by Tyler-IN** [comment]
Closing assuming this is fixed in the mod presently.
