### ISSUE TITLE
Dev Suggestion: Quick bugfix release

### ISSUE THREAD

**Issue by iPherian** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#234]
There seem to be a few bugs which are already fixed in dev and have gotten reported quite a bit (see the linked duplicates in #169), perhaps we could release now? Or if necessary, spin off just the fixes and release it?

issue #169 
issue #207

**Comment by Tyler-IN** [comment]
Yeah. I'm forgoing the rebase & 2 review requirement so we can pack things down into dev and put out a RC.

**Comment by KenRiehle** [comment]
https://drive.google.com/open?id=1AW12ffMjBGFIO_ZgaIQ2O_rXr4ZdDwUQ

Tyler please watch that 30 second video and tell me if this is your mod or not. It says applied patches and skipping patches. Not sure why it is picking and choosing what patches to apply and which to skip. This is a brand new character that I just started as a test.

**Comment by iPherian** [comment]
@Tyler-IN Perhaps we can do a full release to nexus? A lot of people probably don't even know that releases are on here, so they've still got the buggy version on there. I don't think it needs a ton of features as long as it's got the mentioned bugfixes.

**Comment by Tyler-IN** [comment]
That was kind of the point with early RCs, I don't need overwhelming feedback of "everything is broken" - the current builds from dev are looking much better than RC 2, with more working components. I want to get these current pulls dealt with and then one more round of testing and push to Nexus.

**Comment by iPherian** [comment]
> You're a little bit out of the loop if you're not on the Discord with us, @iPherian :)

@Tyler-IN I guess I am ;) my discord is [ipherian#5005](https://discordapp.com/users/698206339306094603)

**Comment by Tyler-IN** [comment]
Yeah this is Community Patch. The skipped patches can't be applied because
either they no longer apply to the current game version, either because
they need to be fixed to work with that version or they are already fixed
in the base game.
