### ISSUE TITLE
0.1.0-rc2 Diagnostics aren't copying to clipboard

### ISSUE THREAD

**Issue by Kahchow** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#238]
Game Version: e1.2.1
Mod Version: 0.1.0-rc2

Hi there, I've been using Community Patch to try and fix crashing issues with Yell To Inspire, but since the recent release, I've been unable to get automatic diagnostics to copy or save anywhere. Not sure if it's an issue with my mod, but I haven't changed anything since e1.1.0 and currently facing quite a bit of CTD issues.

EDIT: Upon crash it triggers just the vanilla crash message as well, instead of a message-less CTD + diagnostic report that I was experiencing prior.

**Comment by Tyler-IN** [comment]
Can you contact me on Discord for quicker response? We'll try to coordinate there.

A number of things have changed w/ the exception handling, for example the handler no longer attempts to wrap Tick exceptions or Event based exceptions as other mods are injecting mechanisms there instead.

If other mods are loaded and prevent exceptions from arriving at the AppDomain UnhandledException event, there will be no automatic report generated.

Do manually generated diagnostic reports also not work? (e.g. hitting the option from the menu)

**Comment by Tyler-IN** [comment]
I have someone in the Discord channel right now who's able to use the manual diag. report feature in rc2.

**Comment by Kahchow** [comment]
Messaged you on Discord, but yes, manual diag works fine. My mod uses tick functions pretty extensively so that probably explains why it's not working for me, but in that case it's a lot more difficult to find where 1.2.1 and 1.3.0 are breaking with it.
