### ISSUE TITLE
CTD on game start

### ISSUE THREAD

**Issue by gradashy** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#24]
Game version is 1.0.5 and mod at 0.0.1

Tried to load alone or with other mods, always CDT.

**Comment by KenRiehle** [comment]
have you disabled all other mods , and try it, then disable this mod and try it and see if there is any change. If you crash with all mods disabled you might have a corrupted save file also how far do you get before you CTD? Sorry I'm helping the Dev Tyler.

**Comment by ArujBarbaross** [comment]
Had this issue as well, it's resolved by #6

**Comment by gradashy** [comment]
Not a bug, I forget the unblock thing. So it is my fault.
