### ISSUE TITLE
Game crash on startup with cheatmode on

### ISSUE THREAD

**Issue by peren717** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#241]
I can confirm now. With cheat mode on, the game crash on startup. Otherwise, it works perfectly.

**Comment by Tyler-IN** [comment]
What version of Community Patch are you using? Any other mods?

Also, most if not all of our devs test with cheat mode on, so...

**Comment by iPherian** [comment]
Yeah I always test with cheat mode on

@peren717 in addition to tyler's questions, are you using an alternate launcher? Does it work without the other mods and without the alternate launcher?

**Comment by peren717** [comment]
v0.0.2-hotfix-5. I uninstalled Vortex and I did a clean re-install of the base game, so that problem went away... I think it might be a bug introduced by Vortex.
