### ISSUE TITLE
Startup CTD bug (caused by beta hotfix 1.3.1?)

### ISSUE THREAD

**Issue by bonerstorm69** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#243]
So a couple friends and I have had nothing but CTD from startup for about 5 hours now.  It may have something to do with the 1.3.1 beta hotfix (which we definitely remember downloading but seems to have disappeared down the memory hole - no patchnotes on TW websites).  Validated files and 7 files DL'ed later nothing changed.

I did exhaustive testing.  First thing I figured out was that even with all mods turned off, I still had CTD.  However, the CTD's stopped if I moved all mods out of the Modules folder.  I tested further and figured out that ONLY the Community Patch was causing the CTD when turned off in folder.

So I went here and downloaded the prerelease new patch and also antijank.  Putting the prerelease in the folder stopped the crashes on startup... but only so long as it was turned off.  Turning it on still CTD.

Then I installed antijank and that seems to have done nothing much.  The functions in the loader including diag were active and they showed "missing file" errors for antijank... so there's that?  Saving and loading mod order worked too.  Game would still startup as long as no mods were turned on. 

So I got rid of antijank and started turning on each mod one by one.  It looks like this CTD happens with not only prerelease Community Patch, but also Modlib and MBOptionScreen too... and by extension every mod that depends on them.

What the heck did they do???  It looks like they broke every mod that adds an options menu except for AutoTrader.

Thanks so much for all your hard work guys.  You're my heroes.

**Comment by bonerstorm69** [comment]
Of course I did the powershell unlock thing but I'm pretty sure that's not an issue with me anyway.  I must have some switch flipped where my DLL's are never locked.

**Comment by bonerstorm69** [comment]
Maybe this will be helpful in ID'ing what's busted...

CONFIRMED WORKING:
Traits Mod
Recruitable
Frugal Cavalry
Developer Console
AutoTrader

CONFIRMED CAUSES CTD:
ModLib
Bannerlord Tweaks
Training Tweak
Garrison Improvements
Option Screen Standalone
Realistic Battle
Community Patch

**Comment by bonerstorm69** [comment]
OK I tweaked and tested and redownloaded and also made sure that I didn't accidentally rename the folders (because I'm an idiot and at some point wondered if by changing folder name I could fix the load order).

After applying the newest CP release AND antijank... it works!  Mostly!

I still can't load GarrisonImprovements but I'm guessing that's a problem with MBOptionScreen... so not y'all's problem.

If you could provide any insight, though, that'd be greatly appreciated.

**Comment by Urijahuri** [comment]
2.0.9 of MBOptionScreen fixes any issue it had with this version of Community Patch, removes the need to install Modlib for any mods, and seems to fix any issue it had with GarrisonImprovements

**Comment by bonerstorm69** [comment]
YOU ARE MY HERO!

I just checked and MBOS does work and obviates the need for ModLib... but it also looks like Garrison Improvements still causes CTD's on startup and will continue to until the modder posts an update compatible with the new version.  C'est la vie.

Regardless, I guess that ain't your problem.  I'll close this out.  Thanks so much!
