### ISSUE TITLE
BMTournamentXP crashing on startup (not related to CommunityPatch)

### ISSUE THREAD

**Issue by Tyler-IN** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#25]
![image](https://user-images.githubusercontent.com/33945568/78590442-dadd4c00-780f-11ea-84de-c1937611707c.png)

**Comment by TYoung86** [comment]
The Tournament XP mod has types that refer to assemblies that it cannot access at this point in the loading process.

See the https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/9 for an example of a solution.

**Comment by Tyler-IN** [comment]
The Tournament XP mod has types that refer to assemblies that it cannot access at this point in the loading process.

See the https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/9 for an example of a solution.

**Comment by KenRiehle** [comment]
hey Tyler did you get my posts?

**Comment by Tyler-IN** [comment]
maybe, did you get my posts?
