### ISSUE TITLE
0.1.0-rc2: Riding Bow Expert doesn't work in 0.1.0-rc2 + latest 1.3.0 BETA

### ISSUE THREAD

**Issue by famaouzi** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#254]
Title, I downloaded 0.1.0-rc2 CPatch and tried in current save (without CPatch) 1.3.0 BETA, and it doesn't work when I bought noble longbow and tried it in the village

**Comment by ajseavey** [comment]
Hmmm. I just tested this in my game. I did have the patch applied beforehand, but on 1.3.0 Beta I cleared my perks/skills, set my riding skill to high enough to be able to add the perk, added it and went from not being able to equip it on horseback when visiting a village to being able to use it. Also double checked the alternate crossbow perk at that level and that works too. Using 10.2rc2 downloaded from the releases here.

Have you confirmed that the patch is working in general? I.E. are other perks this patch fixes working?

**Comment by famaouzi** [comment]
> Have you confirmed that the patch is working in general? I.E. are other perks this patch fixes working?

Yes, because the arrows are increased in-battle (it is not working in vanilla, right?). Note that this is not the only mod I activate, when I deactivate other mods, the save won't load.

**Comment by ajseavey** [comment]
Hmmm. Could you get a diagnostic report from in game after you load a save. After the save has loaded you can go to the Community Patch Options and select something along the lines of `Generate Diagnostic Report`. Once you've done that paste the result here. IIRC it automatically copies to your clipboard.

**Comment by Tyler-IN** [comment]
Not 100% sure, but this should be resolved in current RC. Re-open as needed.
