### ISSUE TITLE
Crash when joining Tournament - when loading into specific match

### ISSUE THREAD

**Issue by brandonm4** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#258]
Crash when you join the match itself.  You can enter the Tournament, Bet, Skip Rounds, but when you Join to play the match game crashes.  There is no exception window.

This is using v0.0.2 compiled from dev branch  (against 1.3.0 BL)  running on 1.3.0 beta so maybe a known issue.  
I tried without tournamentsxpanded as well just to make sure it wasn't a conflict there.  From the messages at start it appears all the patches patch.

When community patch is not loaded, I can enter that match.

I could not find a diagnostics log in \Documents\Mount and Blade II Bannerlord (or at least not a current one).

**Comment by Tyler-IN** [comment]
I sent you an invite to the dev discord.
![image](https://user-images.githubusercontent.com/33945568/80844273-4c70a600-8bd4-11ea-91f4-d54233fb8303.png)

If you're referring to this patch, a fix was already pushed to dev - possibly near the time you posted this.
![image](https://cdn.discordapp.com/attachments/701000420398465054/705862609672470609/Screenshot_1608.jpg)

**Comment by brandonm4** [comment]
Yes - latest pull has fixed it
