### ISSUE TITLE
Bandits have all become babies 

### ISSUE THREAD

**Issue by GruntyThrst** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#260]
Community patch installed through Vortex (0.1.0-rc2) into an in progress campaign. No issues so far except all bandit classes use the baby model now. Adorable, but baby forest bandits are a nightmare.

_Invincible_ babies, apparently. Hitbox must be wacky.

**Comment by Tyler-IN** [comment]
Duplicates https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/208

We don't mess with the age model. Are you sure it's not some other mod?

**Comment by x106x** [comment]
I was just looking at building the patch for the first time and am having trouble and saw this.  If you don't have the name specified properly for the base character of a troop, it will use a baby.  I don't know if this mod is working with troops but that's what it's related to.

**Comment by GruntyThrst** [comment]
> 
> 
> Duplicates #208
> 
> We don't mess with the age model. Are you sure it's not some other mod?

None of the other mods I was using (Character Import/Export, Developer Console, Monty's Forge Overhaul, and Settlement Icons) should touch the troops, AFAIK. Looking at fumblesneeze's comment on #208, I suspect it was just an error resulting from the mess of installing/uninstalling I was doing to try and troubleshoot some crashes.  I've included the save in case it ends up being useful.

[save_002.zip](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4569425/save_002.zip)

**Comment by Tyler-IN** [comment]
> I was just looking at building the patch for the first time and am having trouble and saw this. If you don't have the name specified properly for the base character of a troop, it will use a baby. I don't know if this mod is working with troops but that's what it's related to.

We don't have any XML components to the mod at present.

**Comment by Tyler-IN** [comment]
Closing as stale - no tester seems to be able to reproduce, outside of intentionally breaking a mod install or screwing up native module xml files. The saves are stuck with babies, there's no real way around that outside of editing the save games.
