### ISSUE TITLE
Intellisense auto complete not working (VS2019)

### ISSUE THREAD

**Issue by iPherian** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#261]
VS2019's auto complete doesn't seem to work with this project. And virtually all of the using statements in files are highlighted by VS as being unnecessary (incorrectly).

You know what's really strange tho?

You can get it all working again by commenting [this line](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/blame/9805508ecb7a62680f4bc9a786550408f85925cb/src/CommunityPatch/CommunityPatch.csproj#L107) for the SourceRevisionId property.

```xml
<!--<SourceRevisionId>$(SourceRevisionId.Substring(0,7))</SourceRevisionId>-->
```

![](https://i.imgur.com/kpUfIex.gif)

That line seems to be related to the dll version when you build so I guess i'll just keep it commented locally for now. Curious tho.

**Comment by xahon** [comment]
https://www.nexusmods.com/mountandblade2bannerlord/mods/186?tab=description

> use JetBrains Rider as an IDE, load the CommunityPatch.sln solution file.

**Comment by iPherian** [comment]
> https://www.nexusmods.com/mountandblade2bannerlord/mods/186?tab=description
> 
> > use JetBrains Rider as an IDE, load the CommunityPatch.sln solution file.

Idk I can't afford it and i'm not a student. I did just notice that they give out [free licenses](https://www.jetbrains.com/community/opensource/) to open source projects (which we are) which is pretty cool. Idk how that works though.

**Comment by xahon** [comment]
@iPherian you can use 30-days evaluation which includes all features (even for commercial purposes) or you can hack it and use for free (but only versions <= 2019.3)

**Comment by iPherian** [comment]
> I don't think that project meets jebrains open source criterias, it should have > 500 contributors (if i recall correctly)

@xahon That would be a shame. You sure tho? I can't find that requirement anywhere.

**Comment by Skau** [comment]
Back when the project first started @Tyler-IN talked about open source licenses for Rider. Not sure what happened. BTW > 500 contributors is not a requirement.
