### ISSUE TITLE
GetThisParamType missing method

### ISSUE THREAD

**Issue by xahon** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#262]
I ran project in rider and a single unresolved reference stopped me from making build

https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/blob/9805508ecb7a62680f4bc9a786550408f85925cb/tools/Antijank/MbEventExceptionHandler.cs#L51

---
Rider shows no available reference, google shows no useful info about the method

**Comment by Tyler-IN** [comment]
MbEventExceptionHandler shouldn't be wired up, but GetThisParamType is defined in MonoMod.Utils inside Harmony, I'll probably remove it's usage or copy it into the project.
```cs
        public static Type GetThisParamType(this MethodBase method) {
            Type type = method.DeclaringType;
            if (type.IsValueType)
                type = type.MakeByRefType();
            return type;
        }
```

**Comment by Tyler-IN** [comment]
An implementation of GetThisParamType is added to Antijank now.
