### ISSUE TITLE
Launcher doesn't work after appliyng Antijank

### ISSUE THREAD

**Issue by xahon** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#264]
The laucher doesn't actually launch itself after I made a build of that project.
It shows this  
![image](https://user-images.githubusercontent.com/18731681/80913953-b7181200-8d8b-11ea-8c31-f7c4e5a05547.png)
But after i press 'ok' - nothing happens
If i run `Bannerlord.exe` or `Bannerlord_BE.exe` or `Bannerlord.Native.exe` - game starts, but i'm unable to choose mods i want before it starts

---

Ok, i restored game from steam, created a repository in `MnB2/bin/Win64_Shipping_Client`, rebuilt again and checked git diff

> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
>         0Harmony.dll
>         Antijank.Debugger.dll
>         Antijank.dll
>         AntijankProfiler.dll
>         Bannerlord.exe.config
>         TaleWorlds.MountAndBlade.Launcher.exe.config

Removing these files:  
>         Bannerlord.exe.config
>         TaleWorlds.MountAndBlade.Launcher.exe.config

fixed the launcher

**Comment by Tyler-IN** [comment]
If you want support for Antijank, contact me on Discord.
