### ISSUE TITLE
Performance drop

### ISSUE THREAD

**Issue by peppermor** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#266]
After I launched game with mod builded from 9805508ecb7a62680f4bc9a786550408f85925cb on dev I encounter huge FPS drops on global map. No difference in battle only on campaing map. When on 2x speed it drops from 144fps to 13fps, drops are not so big when game speed is normal(x1). Confirmed that without this mod game runs smoothly

**Comment by Tyler-IN** [comment]
Yeah, I missed the caching bit. Rebuild with latest.

**Comment by peppermor** [comment]
Confirm after rebuilding from latest issu fixed

**Comment by iMcLee** [comment]
I have now this fps drop. On map 20 fps.
