### ISSUE TITLE
Can't get mod to work (CTD) (1.3 Beta)

### ISSUE THREAD

**Issue by Raganvad** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#271]
Discovered this mod, got excited for the perk fixes, but I get a crash on startup no matter what I do. Tried: With no other enabled mods and the mod at the bottom of load order, verified steam files, deleted and reinstalled mod, redownloaded mod, deleted old install and re-install, verified the mod was in the correct location C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules unpacked mod with 7zip in Modules folder and MnB2-Bannerlord-CommunityPatch-dev folder was created successfully. I run Windows 7, help would be much appreciated...

**Comment by peppermor** [comment]
Mod folder NEED to be named just CommunityPatch

**Comment by peppermor** [comment]
Also if you just downloaded source code not release pack you need to build it first.

**Comment by Raganvad** [comment]
Yup, downloaded source code like a doofus, i got the release pack working, may try building the dev version in the future, thank you!
