### ISSUE TITLE
Lost benefits of the "Ultimate Leader" perk when joining a faction

### ISSUE THREAD

**Issue by Solganis** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#275]
as a Mercenary or a Vassal. It's just vanished from a "Party Troop Size Limit" window.

Text in this perk stated, that, you need to be a "Clan Leader" for this perk to work.

Clan Leader =/ Faction Leader. 

So, I should retain the benefits of that perk. (???)

/ I'am using the latest Dev
/ 1.4 Beta

**Comment by ACiDxCHRiST** [comment]
Confirmed. The perk and bonus are working if you are unaffiliated or if you are leader of your own kingdom, but if you become a mercenary or vassal, the troop limit bonus effect and tooltip disappears.

"Leadership>Ultimate Leader"
(Clan Leader)
Every skill increase after 250 gives you +1 party size.(Active)

**Comment by Tyler-IN** [comment]
FYI, we don't have a patch to fix Ultimate Leader, this would be a bug in the base game we need to fix.

**Comment by Solganis** [comment]
https://www.nexusmods.com/mountandblade2bannerlord/mods/373?tab=description

This mod seems to fix (I didn't tried it yet) Ultimate Leader and other perks with party size too.

Maybe, you can cooperate with him and implement his fixes to Community Patch?

**Comment by Tyler-IN** [comment]
I think I've had trouble reaching out to neatedique before...

**Comment by Solganis** [comment]
You can add this perk to "Readme" now in "Leadership" section as fixed (implemented)

I tested it, it work's in game (for now)

**Comment by iPherian** [comment]
@Solganis thanks!

**Comment by Solganis** [comment]
@iPherian no, YOU!
