### ISSUE TITLE
[Stable-v1.3.1]Game crash when talking to new companion at tervin

### ISSUE THREAD

**Issue by Phanquan** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#277]
As the title as, when using the mod, I got crash when trying to talk to any companions.

**Comment by Tyler-IN** [comment]
Could you upload a zip of the save game demonstrating the problem?
Preferably with a low mod count.

**Comment by welshace** [comment]
Also this .. having tested it, I have systematically tested it with and without all mods i was using, and it is crashing on a clean build of the game with just modlib and comm patch loaded..

I'm on 1.4 beta  with  Modlib Beta 1.4 and the v0.1.0-rc3 version of your patch .. though i havent tried with the newest patch on..

**Comment by wand-r** [comment]
I'm having a similar problem. I'm just using comm patch with a new game. When I try to pay for the companion there are no choice available to select and I cannot exit the conversation. A lot of the time the game will crash soon after. 

Also if I boot up a save after crashing, the companion I was talking to while I crashed will not be at the same castle. It takes a few days or so for them to pop up at a different location.

Not sure if this is related, but sometimes when introducing myself, I will get the line ERROR: CHARACTER_NAME_SCREEN variable has not been set before, where the companion name should be. 

Thank you for your hard work. Hope this helps.

**Comment by Tyler-IN** [comment]
@Phanquan @welshace can you confirm works with rc5?

**Comment by Phanquan** [comment]
Hi @Tyler-IN,

After the new version, I havent faced any above error in 2 days, thanks for your wonderful fix.

Regards.
