### ISSUE TITLE
Applied check missing in TraitFixesPatch?

### ISSUE THREAD

**Issue by AlcoholV** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#283]
Each time load a save, one more trait log message is duplicated.
After looking at the source code, set Applied to true phrase seems to be missing. 
Please check.

**Comment by Tyler-IN** [comment]
What build are you using?

**Comment by AlcoholV** [comment]
> What build are you using?

Dev Branch version.
I fixed it as I said and built it, and it worked well.
