### ISSUE TITLE
Prominence doesn't work

### ISSUE THREAD

**Issue by tynakuh** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#29]
Should receive +1 influence as a vassal.

**Comment by Skau** [comment]
Optimally this would also require a tooltip addition so the influence gain tick makes sense. If we just patch it so it adds one extra if Prominence + is vassal,, the tooltip will be off by one.

**Comment by tynakuh** [comment]
Yea, I have a fix already at:
https://www.nexusmods.com/mountandblade2bannerlord/mods/172

Just need to port this one over.

**Comment by Skau** [comment]
Great! I'd love to see the code. Not really digged into UI much yet.

**Comment by tynakuh** [comment]
I replaced the models in my original approach, I like the look of your approach you did on the other fixes though! Far more resilient to other mods coming along.  

I'll probably get on this later tonight after finishing off work.
