### ISSUE TITLE
Accessing Clan Screen Crashes Game with Latest Beta 1.4 Hotfix

### ISSUE THREAD

**Issue by PraxisLP** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#291]
The latest beta 1.4 hotfix has made trying to access the Clan screen (either by clicking or by hotkey) cause the game to crash when using the CommunityPatch mod.

Turning the mod off fixes the problem.

The beta hotfix was released around 17h30 EDT on May 11th 2020.

**Comment by Tyler-IN** [comment]
This is v0.1.0-rc4 or v0.1.0-rc3?

**Comment by Solganis** [comment]
@PraxisLP try this release - https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/tag/v0.1.0-rc4

it has been pushed to Nexus too

**Comment by Figulus** [comment]
Had the clan prob too , v0.1.0-rc4 cures it! Quick work thanks.

**Comment by Figulus** [comment]
Edit ; Spoke to soon...clan button works but just got ctd in battle and the error message cites community patch.

**Comment by Solganis** [comment]
> 
> 
> Edit ; Spoke to soon...clan button works but just got ctd in battle and the error message cites community patch.

https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/293

**Comment by PraxisLP** [comment]
So... I will wait until #293 gets resolved to try it again? Can't be having crashed mid-battle!

**Comment by PraxisLP** [comment]
That being said, I will try the latest release candidate to ensure that this issue is resolved so we can close the issue.

**Comment by Tyler-IN** [comment]
> Edit ; Spoke to soon...clan button works but just got ctd in battle and the error message cites community patch.

Clan

**Comment by PraxisLP** [comment]
Can confirm that it's fixed on my end. Thanks for the amazingly quick fix!

**Comment by Figulus** [comment]
Trying rc5

**Comment by PraxisLP** [comment]
I had no issues when I tested rc5. Gonna keep playing with that. Thanks again!

**Comment by Figulus** [comment]
Just been through a battle and no crash. Thanks also for quick fix!
