### ISSUE TITLE
FPS drop on map

### ISSUE THREAD

**Issue by iMcLee** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#296]
Have drop fps to 20 from 144 on map. When added this mod. Without all is ok
1.3.1

**Comment by muzica9** [comment]
+1. 

beta 1.4.0

**Comment by Tyler-IN** [comment]
Duplicate - refer to https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/301
