### ISSUE TITLE
Cannot earn Scouting experience

### ISSUE THREAD

**Issue by VBMeireles** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#297]
I started a new game on 1.3 (non-beta) and noticed I wasn't earning any Scouting experience despite Bannerlord Tweaks giving x5 to everything. I removed Community Patch (and nothing else) and am earning Scouting experience again.

**Comment by Bravix9** [comment]
Have had no issues earning scouting xp with a game started during 1.3 beta, now in 1.3 stable. I don't have Bannerlord Tweaks installed.

**Comment by Tyler-IN** [comment]
With Community Patch active, generate a diagnostic report (under Community Patch Options) and upload it here. We'll look into it.

**Comment by VBMeireles** [comment]
Alright. Turned it back on and I'm indeed receiving Scouting experience. That's weird, but it happened, and I turned only Community Patch off and resumed earning Scouting experience. That's what made me certain it was the cause.
