### ISSUE TITLE
Duplicate "(x new parts)" string [Bannerlord Tweaks]

### ISSUE THREAD

**Issue by VBMeireles** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#298]
Bannerlord Tweaks tells me how many parts, if any, I will unlock from smelting an item. Community Patch turns "Eastern Light Mace (2 new parts)" into "Eastern Light Mace (2 new parts) (2 new parts)". The string is triplicated for 3 new parts and quadruplicated for 4 new parts. The issue is new. I used the previous version (of Community Patch) along with Bannerlord Tweaks in my 1.2 (non-beta) game and the strings were not duplicated then.

**Comment by VBMeireles** [comment]
I turned Community Patch back on and the "new part(s)" strings aren't being multiplied so it's probably not the cause.

**Comment by VBMeireles** [comment]
![image](https://user-images.githubusercontent.com/65229421/81753341-f4665900-9489-11ea-89b1-e281164560fe.png)

It started to happen again after a reload.

**Comment by Tyler-IN** [comment]
Without community patch loaded, could you try smithing, reloading, smithing again, etc. to see if it duplicates @VBMeireles ?

**Comment by VBMeireles** [comment]
![image](https://user-images.githubusercontent.com/65229421/81917179-3b983b00-95ab-11ea-8532-9ad9f35c6725.png)
This is with Community Patch on (I always leave it on - turned it off, got into the game to check and out, then turned it back on and got back into the game to check - no issues) which indicates it might not be the root of the problem. Maybe incompatibilities might cause it? I'd never had it before installing Community Patch 1.3, and I used 1.2.

I can't seem to replicate the issue reliably. It's erractic. The only thing I can say for sure is I've never had the problem without Community Patch. Whenever it happened, Community Patch was on. Turning it off always immediately solved the problem, however turning it on doesn't bring it back immediately.

I'll keep playing (it usually happens after some time) and inform you.

**Comment by VBMeireles** [comment]
...and surprise! I made no changes. Bannerlord Tweaks, Community Patch and the same other mods in the last report are still on with no changes made to any options whatsoever since I posted my last screenshot without the issue. After a couple of fights and deciding to go do some smelting, the duplicate strings are back.
![image](https://user-images.githubusercontent.com/65229421/81942737-e53df300-95d0-11ea-9cb7-2f5ce9810791.png)

**Comment by VBMeireles** [comment]
Restarting the game temporarily fixes the issue. Just restarted and it's gone. No changes made to any mods. It's starting to look like an incompatibility issue more on Bannerlord Tweak's side than on Community Patch's, since BT is responsible for the string.

**Comment by VBMeireles** [comment]
Closing the issue now because it's a Bannerlord Tweaks issue alone. It's not related to Community Patch, since I just had the issue without Community Patch enabled at all (in 1.4.1).
![image](https://user-images.githubusercontent.com/65229421/82059524-88a80a00-969c-11ea-9a88-2012d800fd38.png)
