### ISSUE TITLE
freeze hitting enemy while on horse

### ISSUE THREAD

**Issue by blenkor** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#305]
when enemy's weapon hit my horse

**Comment by JoeFwd** [comment]
What was the game's version and community patch's version when this occurred ?
Did you get a crash error ?
I'm quite sure that it is the same bug as discussed in this issue : https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/293

**Comment by blenkor** [comment]
> What was the game's version and community patch's version when this occurred ? What game mode did you use ?
> Did you get a crash error ?
> I'm quite sure that it is the same bug as discussed in this issue : #293

exactly the same bug
CP is the latest on nexus and game is 1.3.1
no error, no log, just froze
i dont think its other mods problem, because i disable CP and it stop occuring

**Comment by JoeFwd** [comment]
I couldn't reproduce this bug with the game at 1.3.1 and the latest CP patch (v0.1.0-rc5) in the campaign mode. 

Although, it does crash/freeze in custom battles. So yeah that's a bug in this game mode that will require fixing.

**Comment by CaptainBoat** [comment]
this should probably be the same issue of 
https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/306

my report also shows that the issue was from trampler

**Comment by Tyler-IN** [comment]
@blenkor What game mode did you use?

@CaptainBoat The other issue is custom battle mode.

**Comment by blenkor** [comment]
> @blenkor What game mode did you use?
> 
> @CaptainBoat The other issue is custom battle mode.
> If these are both custom battle, we'll mark duplicate and close one of these.

i test in custom battle only and froze, didn't try campaign
