### ISSUE TITLE
TramplerPatch crash on 1.3.1 + v0.1.0-rc5 in custom battles

### ISSUE THREAD

**Issue by JoeFwd** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#306]
![crash trampler cutom battle](https://user-images.githubusercontent.com/32904771/81841893-63f04d00-954b-11ea-8f33-84ed0d7e590a.png)

**Comment by CaptainBoat** [comment]
Same problem here

**Comment by CaptainBoat** [comment]
btw how do I disable trampler patch?

**Comment by Tyler-IN** [comment]
@CaptainBoat you are on Game e1.3.1 and Community Patch v0.1.0-rc5?

**Comment by Tyler-IN** [comment]
This will be fixed in an upcoming RC, but it currently only seems to affect custom battles.
