### ISSUE TITLE
Unable to recruit tier 5 and tier 6 units

### ISSUE THREAD

**Issue by desmondw** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#310]
I've had 10+ tier 5 and tier 6 in my prisoner party for over a year of in-game time and don't recall seeing any of them become available to convert into party. Is this community patch fix still working?

On the latest beta patch.

**Comment by Tyler-IN** [comment]
https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/114

**Comment by desmondw** [comment]
Per above link it appears that it was previously implemented in this mod but has since been removed as it appeared to be intended by the MB2 developers.
