### ISSUE TITLE
raise the meek

### ISSUE THREAD

**Issue by jonb12334** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#314]
Seems to add medium XP to entire stack, rather than medium xp to each member of the stack. Is this working as intended?

**Comment by Tyler-IN** [comment]
http://www.bannerlordperks.com/perk;skill=leadership;perk=raise-the-meek

**Comment by JoeFwd** [comment]
Talewords fixed this perk in e1.4.2. Closing
