### ISSUE TITLE
Breaking API changes in e1.4.1

### ISSUE THREAD

**Issue by Tyler-IN** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#315]
Need to watch to see if they backport those API changes to previous version branches.

**Comment by Tyler-IN** [comment]
Dev now builds with e1.4.1 but breaks with e1.4.0.

**Comment by Tyler-IN** [comment]
Test build is up in dev. discord #community-patch-testing

**Comment by Tyler-IN** [comment]
Multiple testers have confirmed the e1.4.1 patch worked without issues. Re-uploaded.

**Comment by Berdomax1** [comment]
Every time when i load my saved game its crashed in the loading screen.
