### ISSUE TITLE
TramplerPatch2 error

### ISSUE THREAD

**Issue by BroNobodycares** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#316]
I got a  javelin in the face and this popped up. 

![image](https://user-images.githubusercontent.com/65381850/82008104-d17aa700-9639-11ea-9ae3-5a943a77caf6.png)

**Comment by Tyler-IN** [comment]
You *might* have a diagnostic report text file in `Documents\Mount and Blade II Bannerlord` if you didn't terminate the game after getting the popup.

I am really starting to wish ModLib didn't generate these popups for *every mod*...
If you just hit X or Ok, you should have gotten the upload bug report thing, and said yes/no to it, right?
If so, then the Community Patch should have generated that diagnostic report.

It will have all the details I need to figure out what went wrong here.

If you don't have the diagnostic report, I need the release (e.g. v0.1.0-rc5) informational version of the mod (e.g. v0.1.0-a1b2c3d) used, the game version (e.g. e1.4.0.123456), and what game mode (single/custom battle/other) you were playing.

**Comment by BroNobodycares** [comment]
The error occurs during a battles only and it's not consistent.  Crash kills exe, I did not terminate it after pop up.  No bug report pop up.  

Last night I've noticed that there was Community Patch-186-v0-1-0-rc5-1589254727.zip and the problems went away.
