### ISSUE TITLE
1.4.1 beta

### ISSUE THREAD

**Issue by skement** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#320]
Game crashes when i try to open community patch menu. Some of the fixed perks (like horse archery) are working but some are not (like swords as tributes) in 1.4.1 beta. It doesn't say anything specific when it crashes so I don't have anyting about that.

**Comment by Idleness76** [comment]
I see this behaviour in 1.4.1 as soon as I click on "More Options" menu item.  It immediately crashes.  I looked through the .txt files that the crash uploader created but didn't see anything obvious.

**Comment by rangelo009** [comment]
I can attest to this crashing when opening the "More Options" Menu Item. There's a lot of the perks that doesn't seem to be taking effect as well as it did before 1.4.1 beta.

**Comment by Sireaglestrike** [comment]
Khuzait trait also isn't working for me, along with the crash if I look into the community patch options.  Currently not playing because I know as soon as I restart without community patch, community patch will work and I'll want to restart again, lol.

**Comment by Doomlure** [comment]
I can also confirm that the mod doesn't work with the beta branch 1.4.1 as of right now.
I got the exact same problems stated by the lovely people above.

No other information but only waiting patiently for the author to update the amazing mod to work because it's not enjoyable still.

**Comment by Sireaglestrike** [comment]
For sure.  1.4.1 broke a few of my mods, and I would continue playing without most of them...but I'm just waiting for community patch because at least until TW finishes their implementation of perks/traits, I consider this mod essential for how I enjoy this game.

**Comment by Tyler-IN** [comment]
https://www.nexusmods.com/mountandblade2bannerlord/mods/186?tab=files
![image](https://user-images.githubusercontent.com/33945568/82088411-b3578a00-96bf-11ea-9235-3ac6a6c09dfe.png)
Says "For e1.4.0 and below."

On GH releases page;
![image](https://user-images.githubusercontent.com/33945568/82088386-a63a9b00-96bf-11ea-8f99-fde126733e88.png)

**Comment by Idleness76** [comment]
@Tyler-IN thanks for the update.  The one labelled specifically for 1.4.1 - I have installed that and can confirm that the game no longer immediately crashes when I click on the "More Options" menu item.  However, I don't see other expected mods in the list - only the community patch option is present,  Perhaps this is a further problem with modlib?

**Comment by Idleness76** [comment]
Might have spoken a bit too soon @Tyler-IN , sorry.  When I first checked it I had nothing to change when I opened the menu so I used the X in top right to close.  Just now, I closed the menu with the Apply button and crashed.
-----------------------------------------------
Exception occurred inside invoke: ExecuteProcess
Target type: TaleWorlds.Core.ViewModelCollection.PopUpVM
Argument count: 0
Inner message: Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: index
#mscorlib.pdb@{680602FCB99F4C18BF0F837BB4ACA485} (2): 100664125:46
#CommunityPatch.pdb@{F2B696BB47604D67807EDFB6D8D2F995} (1): 100663362:0
#TaleWorlds.Core.ViewModelCollection.pdb@{27E040DCF3D34C948E6F41EAE7E18577} (1): 100663532:143
#mscorlib.pdb@{680602FCB99F4C18BF0F837BB4ACA485} (2): 100667994:18446744073709551615
#mscorlib.pdb@{680602FCB99F4C18BF0F837BB4ACA485} (2): 100681300:57
#mscorlib.pdb@{680602FCB99F4C18BF0F837BB4ACA485} (2): 100681298:108
#TaleWorlds.Library.pdb@{8CF4A16A04AE4B788911D22E166E8788} (1): 100663480:0

**Comment by Tyler-IN** [comment]
Rename this issue or create a new issue with a more specific title if it's still happening.
I'll try to get testers to reproduce.
