### ISSUE TITLE
Most of the perks do not work in "e1.4.1 and up" version of the Community patch

### ISSUE THREAD

**Issue by Constantine5151** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#326]
Hi!
Perks that should increase party size (e.g. Conroi or Merry Men perks) don't work in my case.
I have 39 "Skipted Patch" messages after loading my save game file.
I'm using e.1.4.1 - Beta version of the main game, latest version of the Developer Console mode (1.3.2.) and Community Patch "e1.4.1 and up" version (that was uploaded on 16 May, 5:49AM - information from the Nexus Mods page of the mode).

![image](https://user-images.githubusercontent.com/65441915/82114773-629b6c00-9767-11ea-9474-701f5bb21fe8.png)

![image](https://user-images.githubusercontent.com/65441915/82114742-43044380-9767-11ea-8397-8712e32b1f9f.png)

**Comment by JoeFwd** [comment]
> I'm not sure should I create a new issue for this bug - so let me know if it's should be a separarte issue and I will submit a new one.

Yes, that would make it clearer for devs !

**Comment by Constantine5151** [comment]
> > I'm not sure should I create a new issue for this bug - so let me know if it's should be a separarte issue and I will submit a new one.
> 
> Yes, that would make it clearer !

Thanks, we'll do!

**Comment by rangelo009** [comment]
Just to add the the non-working perks, the Kherjit race buff for speeding up cavalry isn't working with the mod on.

**Comment by largomath2010** [comment]
ultimate leader also doesnt work in 1.4.1

**Comment by cochus1** [comment]
Prominence isnt working neither

**Comment by eli486888** [comment]
Prominence not working, confirm.

**Comment by peppermor** [comment]
Same for supreme authority
