### ISSUE TITLE
Prominence perk not working 1.4.1

### ISSUE THREAD

**Issue by eli486888** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#332]
Hey first thank you all for doing such an amazing job,
I have problem with last update the perk Prominence seems not to work for me, may I ask you guys if you have this issue?

**Comment by JoeFwd** [comment]
Duplicate of https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/318.

**Comment by iPherian** [comment]
Duplicate of #318

**Comment by iPherian** [comment]
I just really like that github timeline note ;)
