### ISSUE TITLE
One step ahead perk not functional in 1.4.0e

### ISSUE THREAD

**Issue by AmonAmarth10** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#341]

**Comment by PaddyVu** [comment]
one step ahead at this fix only enable Party menu when u encounter enemy,this is just a small fix,not real expectation

**Comment by AmonAmarth10** [comment]
I have enabled Menu When Encountering an Army

**Comment by AmonAmarth10** [comment]
There's also (Active) at the end of the description.

**Comment by AmonAmarth10** [comment]
Oh I see what you mean.
