### ISSUE TITLE
Do Two Handed Power Basher and Speed Basher perks work now?

### ISSUE THREAD

**Issue by dolklaphess** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#348]
With or without both perks and using all kinds of weapons (two handed Axe, Short Bill, Great Sword, etc), it does not change the damage displayed when I hit my horse in the village.

**Comment by Sireaglestrike** [comment]
They were never listed as working via Community Patch and 1.4.1 redoes the 2h tree so those perks are no longer in it, so no, they do not work.

**Comment by NicTanghe** [comment]
dolklaphess plz close this request as it wil never be fixed because its unnecessary.
