### ISSUE TITLE
(1.4.1) Crash at daily tick with ".GetRandomAnnexationDecision"

### ISSUE THREAD

**Issue by Solganis** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#353]
Can someone please take a look at this crash with daily tick?
I asked a "Revolutions" and "Diplomacy Fixes" devs about this crash, and they said it's have nothing to do with them. Look's like native.

I have save with crash (1 day ahead) and mods folder are included - https://drive.google.com/file/d/1D4SU4iiyl-pI9G-hSRKU3R2tB-ODLfd7/view?usp=sharing 

```
Source: TaleWorlds.CampaignSystem 
Object reference not set to an instance of an object. 

Inner exception callstack: 
No inner exception was thrown

Outer exception callstack: 
   at TaleWorlds.CampaignSystem.SandBox.CampaignBehaviors.KingdomDecisionProposalBehavior.GetRandomAnnexationDecision(Clan clan)
   at TaleWorlds.CampaignSystem.SandBox.CampaignBehaviors.KingdomDecisionProposalBehavior.DailyTickClan(Clan clan)
   at TaleWorlds.CampaignSystem.MbEvent1.InvokeList(EventHandlerRec1 list, T t)
   at TaleWorlds.CampaignSystem.CampaignEvents.DailyTickClan(Clan clan)
   at TaleWorlds.CampaignSystem.CampaignEventDispatcher.DailyTickClan(Clan clan)
   at TaleWorlds.CampaignSystem.PeriodicTicker`1.PeriodicTickSome(Single timeUnitsElaped)
   at TaleWorlds.CampaignSystem.Campaign.Tick(Single dt)
   at TaleWorlds.CampaignSystem.Campaign.RealTick(Single realDt)
   at TaleWorlds.CampaignSystem.MapState.OnMapModeTick(Single dt)
   at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
   at TaleWorlds.Core.Game.OnTick(Single dt)
   at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)
   at DMD?61844338::OnApplicationTick_Patch1>(Module this, Single dt)
```

**Comment by JoeFwd** [comment]
![crash](https://user-images.githubusercontent.com/32904771/82757487-0a0c4480-9de1-11ea-81e9-f78c35ff1e4f.png)

I captured the same crash in my play through. In my game, the Western Empire and the Comnos clan was already destroyed. I have started this game since day 1, so maybe in new games, we might never see this bug again.

According to the debugger, it would seem like it got a Null value as the random Clan and therefore crash when calling the GetRelationWithClan.

A check to ignore null clan values in the if statement should be enough to avoid the crash.

**Comment by Solganis** [comment]
> 
> 
> ![crash](https://user-images.githubusercontent.com/32904771/82757487-0a0c4480-9de1-11ea-81e9-f78c35ff1e4f.png)
> 
> I captured the same crash in my play through. In my game, the Western Empire and the Comnos clan was already destroyed. I have started this game since day 1, so maybe in new games, we might never see this bug again.
> 
> According to the debugger, it would seem like it got a Null value as the random Clan and therefore crash when calling the GetRelationWithClan.
> 
> A check to ignore null clan values in the if statement should be enough to avoid the crash.

Yeah, I got to the point in the game where I capture every Fief of the Northern Empire. Look's like it's a late game bug with declaring wars/proposals, something along those lines.

It would be magic if someone can include a fix for this. I'm so tired of can't finish a single playthrough. Need to stop using a beta branches, huh.

**Comment by po4emu4man** [comment]
The same issue on my side and a lot of players have it.
Most annoying bug/crash that I was experiencing with Bannerlord so far.

**Comment by JoeFwd** [comment]
Does this still occur with the latest game patches ? @Solganis @po4emu4man

**Comment by po4emu4man** [comment]
No, I didn't get it after hotfix and mods upgrade.

**Comment by Solganis** [comment]
I didn't have a chance to play because most mods didn't updated so far and my game/save crashing in first seconds.

**Comment by Solganis** [comment]
@JoeFwd just tested it.

I still have it in my save.

**Comment by Solganis** [comment]
I managed to bypass it by a method I mentioned above. But dunno for how long.
Also, CustomSpawns are fucked - so as my save than. Waiting for an update for it.

**Comment by Solganis** [comment]
So, bypass work for another several days and then, I got this crash again. Bummer.

Would be great, if someone can make a patch for this. :(

**Comment by Solganis** [comment]
Closing it because no one is gonna fix it anyway, sadly.
