### ISSUE TITLE
Having the latest Community Patch w/ mods causes a crash

### ISSUE THREAD

**Issue by MythyMajestic** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#358]
Everytime I hit the Clan button, the game instantly crashes; no bug report, just dies. I uninstall Community Patch, it opens up just fine.

Just tested it: Running the Community Patch v.o.o.2.2.230030 instantly crashes if I select Clans. I tested this with mods installed, and without mods installed, on a FRESH install of M&B

**Comment by JoeFwd** [comment]
Well, I do not know what game version you are running but the 0.0.2 mod version is outdated. You should get the 0.1.0-rc6 version. It should be compatible with earlier game versions.

If this issue still persists in 0.1.0-rc6 then we will have a look at it.
