### ISSUE TITLE
Crash on game load.

### ISSUE THREAD

**Issue by MasantZA** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#365]
I tried installing this patch today but keep crashing on game load or starting new game. Saw over on the tweaks mod that someone was complaining of something similar today after the game updated (hotfix I think).

**Comment by Hijodeleon** [comment]
The same crash for me with  the game ver 1.4.1

**Comment by horaceborace** [comment]
Same for me. V 1.4.1. Crash logs aswell

[2020-06-02_19.40.08 - kopia.zip](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4719411/2020-06-02_19.40.08.-.kopia.zip)

**Comment by BoomMiD** [comment]
Same thing here, the community patch crashes the 1.4.1 beta when I try to load a save or start a new game.

**Comment by Hijodeleon** [comment]
Hi. Thanks for create the comunity patch. 
But. Are we waiting on an empy lake? Any answer to this posts? 
22 hours since the first one post and no answer. 
Is comunity patch alive?.
Alert!!!! comunity patch is crashing. Not a few games. All games 1.4.1 loading saved games or starting a new game. 
It is so bad our english? Please just say something. 
I think you are working on it. But if is posible just say- Working on it- and then we know Comunity patch is alive.

**Comment by MasantZA** [comment]
For those interested have a look at this https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/362. There are details of an unreleased branch that might be working.

**Comment by Hijodeleon** [comment]
Thanks MasantZA. I saw it. But dont understand what to do with it. Wath i can see is they are working on it

**Comment by MasantZA** [comment]
> Thanks MasantZA. I saw it. But dont understand what to do with it. Wath i can see is they are working on it

Just check about 3/4 way down there's a link (I dunno how safe it is). It's a google drive link. From that you download a zip folder that is the patch. Just unzip in your modules folder where m&b is installed and hopefully, it will work then. My game at least runs now but I still got a crash earlier today from something else.

**Comment by JoeFwd** [comment]
This should be fixed with the newly released rc7 build.

**Comment by Jayell123** [comment]
My game still CTD constantly on campaign start or game start with community patch enabled. I have tried the google drive version and both current builds. Something is wrong with this mod atm.

**Comment by Hijodeleon** [comment]
> 
> 
> > Thanks MasantZA. I saw it. But dont understand what to do with it. Wath i can see is they are working on it
> 
> Just check about 3/4 way down there's a link (I dunno how safe it is). It's a google drive link. From that you download a zip folder that is the patch. Just unzip in your modules folder where m&b is installed and hopefully, it will work then. My game at least runs now but I still got a crash earlier today from something else.
@MasantZA 
yep. I saw it. Thanks for the advice. I will try it and keeping in touch

**Comment by Temu-jin** [comment]
For me the mod started crashing after the game's update today.
