### ISSUE TITLE
Filled to brim not working (1.4.0)

### ISSUE THREAD

**Issue by PaddyVu** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#368]
It just partially work, when i use that perk on my main character,it does increase capacity of carry horse by 20,but when i use it on companion,it doesnt work,still + 20 only,the perk say Party member so it should stack on companion as well

**Comment by JoeFwd** [comment]
Should be fixed with the v0.1.0-rc9 release.
If this persists, it can be reopened.
