### ISSUE TITLE
Mod Options Menus crashing my game

### ISSUE THREAD

**Issue by azirok** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#370]
Any mod, including this one, that has an options menu is crashing my game before I can even get to the main menu on 1.42.  Anybody else?

**Comment by timchu90** [comment]
same here

**Comment by JoeFwd** [comment]
Community Patch won't work for 1.4.2. 

#372 needs to be solved in order to even load the game correctly.

**Comment by ClintRhea** [comment]
Slightly different issue, but related. I can get to the main menu, but clicking "Community Patch Options" instantly crashes the game.
