### ISSUE TITLE
Crash when creating character on stable 1.4.1

### ISSUE THREAD

**Issue by AggressiveJunimo1** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#373]
Whenever I create any character in the new stable e1.4.1, whever I use the community patch, the game crashes immediately after finishing character creation and stat attributes. I have tried using only this mod and fixed mod launcher and yours is the one causing the issue.

**Comment by Jolojose** [comment]
Can confirm! Did the exact same test.

**Comment by johnnydepp18** [comment]
same problem

**Comment by JoeFwd** [comment]
What release are you using ? 

You can try out the [0.1.0-rc7 release](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/download/v0.1.0-rc7/CommunityPatch-e1.4.1-and-up.zip) and see if this still occurs.

**Comment by kducpham** [comment]
It worked ! 1.4.1 Stable branch

**Comment by johnnydepp18** [comment]
Thanks, it worked)

**Comment by PaddyVu** [comment]
> Thanks, it worked)
Show exp only work on 1.4.0,so if u want to use it,u will need to stay at 1.4.0

**Comment by PaddyVu** [comment]
> What release are you using ?
> 
> You can try out the [0.1.0-rc7 release](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/download/v0.1.0-rc7/CommunityPatch-e1.4.1.zip) and see if this still occurs.

What? Rc7,i dont see it in nexusmod,where can i see it?

**Comment by joshualawhead** [comment]
> What? Rc7,i dont see it in nexusmod,where can i see it?

Click the blue text in the comment you quoted (the one by Joe) and it will download the zip file. Once its downloaded, open it and move the "Community Patch" folder to the Modules folder. The most common file-path is:

C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules

**Comment by AggressiveJunimo1** [comment]
> What release are you using ?
> 
> You can try out the [0.1.0-rc7 release](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/download/v0.1.0-rc7/CommunityPatch-e1.4.1.zip) and see if this still occurs.

It works! Thank you so much.

**Comment by JoeFwd** [comment]
This seems to be resolved. Closing.
