### ISSUE TITLE
v0.1.0-rc7 patch installed perks not working

### ISSUE THREAD

**Issue by Hallanvaara** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#377]
Steam downloaded new update (some hotfix just few hours ago) and I decided to uninstall vortex version of community patch which I downloaded from nexus and manually install v0.1.0-rc7 from here.

After extracting files to modules folder and loading up a save I notice party limit has dropped from like 460 to 280 and I don't get any extra party limit or influence from any perks.

Tried deleting files and reinstalling vortex patch but it causes game to crash. Either I somehow made files go nuts or latest hotfix somehow changed something.

**Comment by JoeFwd** [comment]
Last updates on e1.4.1 broke some perks especially those increasing party member limit. I have a fix for that and will release a build soon.

Secondly, Taleworlds nerfed all policies increasing the party member limit in the last e1.4.1 hotfix. That also explains the limit drop.

**Comment by Hallanvaara** [comment]
Dang... I think I'll install mod that increases party limit until I get to my nearest city to drop troops off,definitely won't let tier 5 and 6 guys just run off.

Thanks for fast reply, I'll wait eagerly for your new build. Your doing gods work here.

**Comment by bmkrause** [comment]
> Edit. I also noticed that I lose a lot of gold all of a sudden, did they nerf something else too or raise troop costs?

Check your finances immediately on loading a save (not sure if this is any load or only after a particular patch); sometimes the first day has very high costs relative to subsequent days, especially in non-player parties in your clan.

**Comment by Hallanvaara** [comment]
Yesterday played 1.4.1 and got +5000 a day now I think it was - 5000 a day. Will check tomorrow or after fix what financial exactly say. Good night.

**Comment by devmgrdad** [comment]
It's not just perks that were broken, policies which increase party size were also nerfed. Royal guard and noble retinue does not increase party size as much anymore.

**Comment by bmkrause** [comment]
@JoeFwd Will you be pushing new tentative builds for the new beta/stables?

**Comment by Hallanvaara** [comment]
Tested and perks are working, at least those that increase party size.

Some policies still don't work, for example famous council of commons doesn't give influence at all.

**Comment by JoeFwd** [comment]
This is resolved bu the latest release. Closing.
