### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Luem800** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#381]
the current rc8 release crashes my game on startup. Im using the current stable version of the game. Ive tried other versions, ive tried older versions, ive tried re downloading everything including the game, but the mod still crashes on startup.

**Comment by Swordofheaven** [comment]
Did you make sure to unblock the dll files?

**Comment by Luem800** [comment]
Yep, they are all set to not be read only. As in the box is unchecked.

**Comment by Swordofheaven** [comment]
"This file came from another computer and might be blocked to help protect this computer" with the "unblock" check box? Maybe try using PowerShell to unblock the whole modules folder with "dir -Recurse | Unblock-File".
And you downloaded the 1.4.1 version of rc8?

**Comment by shiaken** [comment]
Does rc8 release works with 1.4.2 beta patch ? i tried both 1.4.1 and 1.4.2 but i got crash on start up .

**Comment by Swordofheaven** [comment]
https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/tag/v0.1.0-rc8

Grab the "CommunityPatch_e1.4.2_and_up.zip" version and make sure to unblock dll.

**Comment by Luem800** [comment]
Yes I downloaded the 1.41 version. I tried the dll unblocker from the nexus and that worked. I dont know why unblocking them manually didnt work, oh well

**Comment by JoeFwd** [comment]
This seems to be resolved. Closing.
