### ISSUE TITLE
Crash when menu opened

### ISSUE THREAD

**Issue by Nevla1** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#387]
Cannot open the Community Tweaks Options on the main menu page, also crashes the game when I try to load a save or start a new one.

Game Version: 1.4.1.231755

Mod Version: 0.1.0.231755

**Comment by JoeFwd** [comment]
What 0.1.0 release candidate did you use ? Do you use  [v.0.1.0-rc8](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/tag/v0.1.0-rc8) ?

**Comment by Nevla1** [comment]
I am using v.0.1.0-rc6
