### ISSUE TITLE
Crashes at launch with 0.1.0 rc9 (from nexus mods)

### ISSUE THREAD

**Issue by Amecareth002** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#390]
As the title says, I thought I would give the mod a chance since it has been updated for the newest updates, 1.4.1 stable and 1.4.2 beta. I'm using the latter one and downloaded the appropriate file (there are 3 on nexus mods). With the patch as the only mod installed, my game crashes as soon as it enters the opening loading screen. I also right-clicked the zip file and unblocked it from there instead of manually unblocking the files one by one. I'm using the fixed launcher mod, version 2.2.1, also from Nexus mod, which automatically sorts the mod at the top. I tried putting the mod after every other "native mod-files" which yields the same result, albeit a little longer delay before crashing.

Deactivating the mod stops my game from crashing.

**Comment by JoeFwd** [comment]
Seems like these is indeed an issue with the e1.4.2+ build. Investigating.

In the meantime, I will take down this download from nexus.

**Comment by Sireaglestrike** [comment]
I downloaded the 1.4.2+ build and it crashes my game on load. Removed all other mods from my folder with only community patch and it still breaks on load.

**Comment by Amecareth002** [comment]
It works fine now indeed. Thanks for your time :)
