### ISSUE TITLE
Huge fps drop when loading with the mod "Attributes reloaded".

### ISSUE THREAD

**Issue by Thornmms** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#392]
[diagnostic-report.20200616211008476.1CC9CEC5.txt](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4789175/diagnostic-report.20200616211008476.1CC9CEC5.txt)

**Comment by Thornmms** [comment]
Game Version 1.4

**Comment by JoeFwd** [comment]
Let me now if this build [CommunityPatch_e1.4.0_and_below.zip](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4794115/CommunityPatch_e1.4.0_and_below.zip) improves your frame rates with this mod.

**Comment by Thornmms** [comment]
Thanks for looking into it. I'm already using the 1.4 and below patch and that's where the problem is.

**Comment by JoeFwd** [comment]
The build uses these [changes](https://github.com/JoeFwd/MnB2-Bannerlord-CommunityPatch/tree/fix-fps-drops). Renamed the download.

**Comment by Mingoss** [comment]
The same is happening for me on 1.4.2

**Comment by Thornmms** [comment]
Awesome, that fixed it! Thanks!
