### ISSUE TITLE
Enable and Disable Menu when encountering a neutral or enemy army. - No option for this present.

### ISSUE THREAD

**Issue by WolfyGreen** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#393]
Look, I am really sorry- I am probably just an idiot. But if this has been implemented, I'm not seeing it anywhere in the options menus. I'm also not entirely sure if I'm out of order submitting an issue about this or not. I searched for it in the Issues already, so I assume it may just be me? Again, sorry if I'm doin' this wrong.

And thank you for all y'all's hard work. 

EDIT: Actually I do believe I misunderstood it, looking at... Uh... #177 now. It's not meant for any encounter like FastDialogue was- Is it to talk to people who are grouped up in armies- like for sieges and whatnot? Again, I apologize.

**Comment by JoeFwd** [comment]
You are not the first one to be confused by this.
Just reminding myself that the name of this option needs to be changed (https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/359#issuecomment-637125920)

As of e1.4.2, being able to talk to other lords in a neutral army is in the base game. So the option was disabled in the latest mod release.

**Comment by WolfyGreen** [comment]
Thanks for the clarification! Keep up the great work! Stay groovy.
