### ISSUE TITLE
Disciplinarian still not working.

### ISSUE THREAD

**Issue by Wesx224** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#4]
Don't know what I've done wrong, but I still don't have the ability to train bandit troops to normal infantry.

**Comment by KenRiehle** [comment]
Yeah same here I downloaded the patch also have 8 troops ready to upgrade and the box is still red and has the you need the perk statement. I triple checked my skills and I have the perk and a skill of 135 in Leadership... does it work for you the guy that created the mod if so what did you do differently?

**Comment by Tyler-IN** [comment]
Re-download the mod and set it up.
Give it a try again.
I had two lines switched around.

**Comment by Tyler-IN** [comment]
Oh - there's something else to cause it to not work, fixing it...

**Comment by Tyler-IN** [comment]
https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/tag/v0.0.1-hotfix1

**Comment by Wesx224** [comment]
Uh, It's saying I need Peak Form.

**Comment by SwankTrain** [comment]
Same as Wesx, the requirement changes to Peak Form but it also auto allocates it regardless of my athletics level. I manually allocated Peak Form after disabling the mod, then re enabled it, and it is still displayed in red.

**Comment by Tyler-IN** [comment]
What the heck... ok, looking into it...

**Comment by Tyler-IN** [comment]
Crap, yeah there's some copy-pasta going on. Fixing it.

**Comment by Tyler-IN** [comment]
https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/tag/0.0.1-hotfix2

Give this a shot. Thanks for testing. I'm not getting enough time to play test it, I'm trying to work out a way to make automated unit tests.

**Comment by slvrbuu** [comment]
It still appears to require Peak Form, at least for me.

**Comment by Tyler-IN** [comment]
I'll post a screenshot in a sec of what it's supposed to look like...

**Comment by slvrbuu** [comment]
I'll start a new game. Maybe some kind of remnant is causing issues.

**Comment by Tyler-IN** [comment]
I am testing it on loading a game, not on new games. It should work on both.

![image](https://user-images.githubusercontent.com/33945568/78455695-dc6f0e80-766d-11ea-869e-57fa8a2624c3.png)

**Comment by slvrbuu** [comment]
Oh, odd. With the mod enabled, Disciplinarian isn't even in the tree.

**Comment by Tyler-IN** [comment]
![image](https://user-images.githubusercontent.com/33945568/78455726-07f1f900-766e-11ea-8308-90d7ea5ba7a6.png)

You might have the wrong version? Try hotfix2

**Comment by Tyler-IN** [comment]
Here's without being skilled up....
![image](https://user-images.githubusercontent.com/33945568/78455787-4a1b3a80-766e-11ea-9960-e0a8e2684861.png)
![image](https://user-images.githubusercontent.com/33945568/78455809-5f906480-766e-11ea-8483-4de07b529949.png)

**Comment by Tyler-IN** [comment]
And here's a screenshot of what it should look like when upgrade is possible...
![image](https://user-images.githubusercontent.com/33945568/78455884-b9912a00-766e-11ea-8444-b7913ccd3dcb.png)
And without the perk...
![image](https://user-images.githubusercontent.com/33945568/78455900-d62d6200-766e-11ea-89eb-44a3aad3a6aa.png)

**Comment by slvrbuu** [comment]
![disc](https://user-images.githubusercontent.com/63139757/78455892-03254900-765e-11ea-8b6c-de3affa1bb57.png)
Yeah, I did some testing, even with no other mods, and cheat_mode = 0, it still doesn't show in the tree.

**Comment by Tyler-IN** [comment]
Alright, guess I need some environmental report functionality for the mod...
I guess I need the versions of everything, the directory structure of the mod's path, and maybe some logs... I'll put together some diagnostic component.

**Comment by slvrbuu** [comment]
The mod is in D:\Games\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules
And my versions/load order is automatically set to:
Native: e1.0.0
Community Patch v0.0.1
CustomBattle: e1.0.4
Sandbox Core: e1.0.4
Sandbox: e1.0.4
StoryMode: e1.0.4

**Comment by slvrbuu** [comment]
I don't know if it matters, but when I try to paste the full path to the .dll, it shows as:
D:\Games\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\CommunityPatch\bin\Win64_Shipping_Client

**Comment by Tyler-IN** [comment]
yeah that looks right, what is the size and some hash of the dll?

**Comment by slvrbuu** [comment]
I'm not sure how to find the hash, but the size is 8KB.

**Comment by Tyler-IN** [comment]
Can you give me the exact size in bytes?

**Comment by slvrbuu** [comment]
8192 bytes.

**Comment by slvrbuu** [comment]
Perhaps the version you uploaded is out of date?

**Comment by Tyler-IN** [comment]
Yep. Uploaded wrong file. Try that one.

**Comment by slvrbuu** [comment]
This one works. :D

**Comment by Tyler-IN** [comment]
Closing as resolved.

**Comment by johnshepardn7117** [comment]
Character Development System patch 1.0.6

Fixed “Leadership Disciplinarian”
