### ISSUE TITLE
Please update Community Patch to 1.5.1

### ISSUE THREAD

**Issue by RinnyZ** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#409]
Due to recent rewamp of ranged perks in 1.5.1 and lots of problems with them, according to https://www.bannerlordperks.com/perk 
new community patch is needed more than ever.

**Comment by tannutuva** [comment]
I second this request!  I love TW but they have a history of really stretching things out, so a lot of people would really appreciate an update.  Not having the perks implemented is a real killer.

**Comment by Kristjan108** [comment]
Thirded, would really like to at least have the old perks working.

**Comment by RinnyZ** [comment]
Big thanks for the update! Though i wonder if ranged perks are working with the patch. They are correctly working at 1.5.3 as far as i tested
