### ISSUE TITLE
Prisoner Recruitment only allows Tier 4 or lower.

### ISSUE THREAD

**Issue by tynakuh** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#47]
Looking at the code:

```
if (!IsPrisonerRecruitable(characterAtIndex) || characterAtIndex.Tier > 6)
{
      continue;
}
```

So Tier 6 shouldn't be recruitable, that's fine but the DefaultPrisonerRecruitmentCalculationModel returns the following:

```
	public override float[] GetDailyRecruitedPrisoners(MobileParty mainParty)
	{
		return new float[5]
		{
			1f,
			0.5f,
			0.3f,
			0.2f,
			0.1f
		};
	}
```
Which is the 'probability' that each tier gets recruited.

However Tier 0 isn't a thing (Well it is, applies to Heroes actually) for troops.
So it's an off by one error, just need to replace that list with something like:

```
	public override float[] GetDailyRecruitedPrisoners(MobileParty mainParty)
	{
		return new float[5]
		{
			1f,
                        1f,
			0.5f,
			0.3f,
			0.2f,
			0.1f
		};
	}

```

for the mod, (Proper fix is of course just decrement the Tier by 1 in the actual code or use a different structure like a Dictionary to determine this, also the method name is a bit confusing...)

**Comment by Tyler-IN** [comment]
It does look like it should be tier 5 or lower instead of tier 4 or lower.

**Comment by tynakuh** [comment]
There's actually an alternative to this instead, looks like this RNG way they have of handling recruitment was a band-aid they slapped on.

The conformity system they have partially implemented looks to be the more intended approach (Given it has UI elements and explaination). Looking into that path may be of value.
I think that should probably be a seperate improvement ticket though.

**Comment by stenellad** [comment]
Can you please explain how this code suggests that Tier 6 prisoners should not be recruitable?
