### ISSUE TITLE
About the DependedModules: Stop doing this.

### ISSUE THREAD

**Issue by bighungryjames** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#53]
I recognized that you show contempt on the people who are adding \<DependedModules\> to your mod's Submodules.xml file. I see that you think emptying that will guarantee your mod to stay on the top on the loading list, right after the native modules.
However, as I observed the default launcher's behavior, I saw that leaving the DependedModules entry empty does NOT guarantee that your mod is loaded before any other mods. The launcher only checks if all the modules have their depended modules loaded before them, nothing more. Having no depended modules has nothing to do with the load order between the mods. In order to have your desired behavior correctly, all of the mods on the Bannerlord Nexus should contain your mod in their depended modules list, not the other way around.
You see, in a multi-participant project, it is really critical to use functions as intuitive as possible. Your approach is, with all due respect, downright confusing. Sure, the launcher assures any non-native modules to load after native modules, but that is a safeguard mechanism. Since your mod actually depends on the native modules, it is much more desirable for your mod's DependedModules list to contain the native modules. That's intuitive. That's how it should be working and how everybody else is expecting it to be working.
I do understand that there is no way to persuade all of the thousands of the modders to add your mod on their DependedModules list.  I do see why you tried that approach. However, since it is not working as intended, it has no gains but it loses the intuitivity. Please stop that. Instead, direct the people to use the FixedLauncher Mod which allows the people to change load order manually.
Perhaps the best solution to this is Taleworlds adding a tag in the Submodules reader function such as {{{HighPriority = "yes"}}} or so. However, until that happens, it is best to follow the way things are intended to be in.

**Comment by Tyler-IN** [comment]
```cs
		// Token: 0x0600000E RID: 14 RVA: 0x00002298 File Offset: 0x00000498
		private void LoadSubModules(bool isMultiplayer)
		{
			List<ModuleInfo> list = ModuleInfo.GetModules().Where((ModuleInfo x) => this.IsVisible(isMultiplayer, x)).ToList<ModuleInfo>();
			list.Sort(new LauncherModuleInitialComparer(list.AsReadOnly()));
			for (int i = 0; i < list.Count; i++)
			{
				ModuleInfo moduleInfo = list[i];
				LauncherModuleVM launcherModuleVM = new LauncherModuleVM(moduleInfo, new Action<LauncherModuleVM, int>(this.ChangeLoadingOrderOf), new Action<LauncherModuleVM>(this.ChangeIsSelectedOf));
				this.Modules.Add(launcherModuleVM);
				UserModData userModData = this._userData.GetUserModData(isMultiplayer, moduleInfo.Id);
				if (userModData != null)
				{
					launcherModuleVM.IsSelected = userModData.IsSelected;
				}
			}
		}
```
```cs
		// Token: 0x0600002B RID: 43 RVA: 0x00002814 File Offset: 0x00000A14
		private bool IsDependant(ModuleInfo source, ModuleInfo target)
		{
			if (source.DependedModuleIds.Contains(target.Id))
			{
				return true;
			}
			using (List<string>.Enumerator enumerator = source.DependedModuleIds.GetEnumerator())
			{
				while (enumerator.MoveNext())
				{
					string sourceDependedModuleId = enumerator.Current;
					source = this._modules.First((ModuleInfo m) => m.Id.Equals(sourceDependedModuleId));
					if (this.IsDependant(source, target))
					{
						return true;
					}
				}
			}
			return false;
```

**Comment by Tyler-IN** [comment]
This mod works fine with the fixed loader and without the fixed loader.

**Comment by bighungryjames** [comment]
Oh, thank you for a fast reply. I recognized I didn't mention it in the original post, but I am using your mod in the middle of the loading order among my mods and it just works fine. My point is, if you truly want your mod to be loaded before any other, use the appropriate method to do so.

**Comment by Tyler-IN** [comment]
The mod does not need dependencies added to it.

Does the mod work without the dependencies?

If not, please help by documenting the errors you encounter.

**Comment by bighungryjames** [comment]
Ok, thank you again for the patient response. I have to admit that I assumed that your mod needs native modules loaded before it, because it changes gameplay. Sorry about that.
![image](https://user-images.githubusercontent.com/47446784/78633818-7983ae80-78dd-11ea-83a9-2e86a832e828.png)
This is the default state of the loading order after I installed the fixed launcher mod. As you can see, the community patch appears above the native modules and it runs fine.

Recorded Unhandled Exceptions:
  None.

Recorded First Chance Exceptions:
  Recording disabled.

Modules Information:
  1. AlwaysKeepHorsesAndFood v0.1.0
    AlwaysKeepHorsesAndFood (AlwaysKeepHorsesAndFood)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  2. BetterTime v1.0.1
    Better Time (BetterTime)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  3. BMTournamentXP e1.2.1
    Tournament XP (BMTournamentXP)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  4. CommunityPatch v0.0.1
    Community Patch (CommunityPatch)
  5. CustomBattle e1.0.6 *Selected*
    CustomBattle (CustomBattle) *Official*
  Dependencies:
    1. Native
    2. SandBoxCore
  6. DeveloperConsole v1.3.1
    Developer Console (DeveloperConsole)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  7. ExperiencePerkFix v1.1.0
    ExperiencePerkFix (ExperiencePerkFix)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  8. FrugalCavalry v1.0.0
    Frugal Cavalry (FrugalCavalry)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  9. InfluenceMod v1.0.0
    Influence Mod (InfluenceMod)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  10. Native e1.0.0 *Selected*
    Native (Native) *Official*
  11. RangedWeapons v1.0.0
    Ranged Weapon Tweaks (RangedWeapons)
  Dependencies:
    1. Native
    2. Sandbox
    3. SandBoxCore
    4. StoryMode
  12. Recruitable v1.0.0
    Recruitable (Recruitable)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. StoryMode
  13. Sandbox e1.0.6 *Selected*
    Sandbox (SandBox) *Official*
  Dependencies:
    1. Native
    2. SandBoxCore
  14. SandBoxCore e1.0.6 *Selected*
    SandBox Core (SandBoxCore) *Official*
  Dependencies:
    1. Native
  15. StoryMode e1.0.6 *Selected*
    StoryMode (StoryMode) *Official*
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
  16. zUnitFixes v1.0.5
    Unit Stat Fixes (zUnitFixes)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. StoryMode
    5. CustomBattle
  17. zzBannerlordTweaks v1.0.7
    Bannerlord Tweaks (zzBannerlordTweaks)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  18. zzCharacterCreation v1.0.1
    Detailed Character Creation (zzCharacterCreation)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  19. zzzPreventEscape v1.0.0
    Prevent Nobility Escape (zzzPreventEscape)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode

Loaded SubModules:
  1. CommunityPatch.CommunityPatchSubModule, CommunityPatch, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null
  2. TaleWorlds.MountAndBlade.View.ViewSubModule, TaleWorlds.MountAndBlade.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  3. TaleWorlds.MountAndBlade.GauntletUI.GauntletUISubModule, TaleWorlds.MountAndBlade.GauntletUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  4. TaleWorlds.MountAndBlade.CustomBattle.CustomBattleSubModule, TaleWorlds.MountAndBlade.CustomBattle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  5. SandBox.SandBoxSubModule, SandBox, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  6. SandBox.View.SandBoxViewSubModule, SandBox.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  7. SandBox.GauntletUI.SandBoxGauntletUISubModule, SandBox.GauntletUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  8. StoryMode.StoryModeSubModule, StoryMode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  9. StoryMode.View.StoryModeViewSubModule, StoryMode.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  10. StoryMode.GauntletUI.StoryModeGauntletUISubModule, StoryMode.GauntletUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  11. Recruitable.RecruitableSubModule, Recruitable, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  12. AlwaysKeepHorsesAndFood.SubModule, AlwaysKeepHorsesAndFood, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  13. BetterTime.Main, BetterTime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  14. BMTournamentPrizes.BMTournamentPrizesMain, BMTournamentPrizes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  15. DeveloperConsole.SubModule, DeveloperConsole, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  16. ExperiencePerkFix.SubModule, ExperiencePerkFix, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  17. FrugalCavalry.FrugalCavalryModule, FrugalCavalry, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  18. InfluenceMod.MySubModule, InfluenceMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  19. BannerlordTweaks.SubModule, BannerlordTweaks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  20. CharacterCreation.SubModule, CharacterCreation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  21. PreventEscape.PreventEscapeSubModule, PreventEscape, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  22. BMTournamentXP.BMTournamentXPMain, BMTournamentXP, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null

System Info:
  gpu: NVIDIA GeForce GTX 1060
  cpu: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  
  GPU Memory: 6061MB
  GC Allocated: 73462128B
  Engine Memory Used: 0MB
  GC Latency Mode: Client Interactive
  GC LOH Compact Mode: Default
  Operating System: Microsoft Windows 10.0.18363 
  Framework Compatibility: .NET Framework 4.8.4150.0
  CPU Info:
    1. Intel Core i7-7700HQ with 4 cores:
      1. MHz °C
      2. MHz °C
      3. MHz °C
      4. MHz °C

And this is the loading order appearing in the launcher before the installation of FixedLauncher mod. The Community patch is between other mods.
![image](https://user-images.githubusercontent.com/47446784/78634344-b8663400-78de-11ea-9a1f-5586273ca486.png)

The game crashes before the title screen.
![image](https://user-images.githubusercontent.com/47446784/78634544-24489c80-78df-11ea-92f9-63223caabf0a.png)

Since the game crashes before the title screen, it was impossible to take the report. Is there any other way?

**Comment by bighungryjames** [comment]
The list of mods I used was identical in both cases. The only difference was the Launcher Fix mod.

**Comment by Tyler-IN** [comment]
Yeah, you have to attach a debugger like Rider or dnSpy to the launcher.

Once the exception occurs, you will see a call frame like this one; https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/25

If it says ReflectionTypeLoadException, it will likely be on the same frame where types are enumerated. The mod will likely show in the local variables of the call frame.
If it's the same scenario as BMTournamentXP, the mod will have types that refer to assemblies that it cannot access at this point in the loading process.

So the crash does not occur with DependedModules added and the original loader used?

**Comment by bighungryjames** [comment]
Oh, that's also possible. That triggers me one idea. Let me go and test it first.

**Comment by bighungryjames** [comment]
Nope, it crashes again *sigh*.
When I saw you mentioning accessing issues, I thought maybe it's about administrator privilege. So I checked the "run with administrator privilege" box in the launcher and tried another shot. But it still crashes without the Launcher Fix.
I really want to avoid installing the .NetFramework in my personal computer and running the debugger. Is that the only option? Also, I do not have C# coding skills. The only thing or two I know about it is the things I learned as an elective at the university.

**Comment by Tyler-IN** [comment]
Rider doesn't come w/ the .NET SDK, I don't think you need to install it to attach the debugger either... not sure though.

If you want direct help troubleshooting, you can contact me on discord and share your screen. I have done this for several other people who were having various problems. There are also a few other knowledgeable modders that may help troubleshoot any mod related issues in there.

**Comment by bighungryjames** [comment]
Well, thank you for the offer, given the time and effort you would have invested doing so, but I don't think I need the help troubleshooting since the Fixed Launcher resolves all of the issues I had. 

I will try to attach the log file with the Rider, but that might take some time.

Besides, any idea why the loading order scrambles without the Fixed Launcher? They are not exactly the alphabetical order of the directory names (I just assumed this again given that some mods changed their directory names by adding zz at their starts).

**Comment by Tyler-IN** [comment]
You should ask the fixed launcher author that question. :)

**Comment by Fumblesneeze** [comment]
@bighungryjames I'm the author of the fixed launcher. To explain it the least technical way as possible, the Comparer-Interface used by the vanilla team only works right if the items are fully equatable, which they are for numbers, e.g. 1 < 3 and 5 > 3 so the comparer will assume 1 < 5 and never check between them, however the relationships between mods aren't simple like this which is why the Comparer is not the right thing here. I've made three mod managers for different games so far, so I have a bit of experience with these things and hacked together a small sorter that works.
