### ISSUE TITLE
 0.0.1-hotfix2 crashes on first splash

### ISSUE THREAD

**Issue by x-x-l** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#6]
and when it doesn't crash the bannerhorse runs forever.

I'd post logs if i could find them. How i can track the cause of error?

**Comment by slvrbuu** [comment]
I've not had any crashes. Is the .dll file unblocked?

Got to ...\Modules\CommunityPatch\bin\Win64_Shipping_Client\
Right click on CommunityPatch.dll and go to properties, and see if there is a button that says unblock.

**Comment by Tyler-IN** [comment]
Thanks for assisting on troubleshooting, @slvrbuu 

I don't know where logging is yet, I'm adding a diagnostics component to the mod soon.

**Comment by x-x-l** [comment]
@slvrbuu Thank you! that took care of it
