### ISSUE TITLE
Suggestion: Mod Settings Framework

### ISSUE THREAD

**Issue by Fumblesneeze** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#61]
Hi, I would like to suggest a mod settings framework that other mods can use.

As an example I would like to recommend Hugslib from the Rimworld Community, as I think it's quite simple and effective to use:

usage example:
https://github.com/Fumblesneeze/RimBetterSpeed/blob/master/Source/BetterSpeed/Mod.cs

source is here:
https://github.com/UnlimitedHugs/RimworldHugsLib/tree/master/Source/Settings

the idea is that you as a user implement a base class where you give it a displayname and then you can add SettingHandle<T> fields to that class and initialize them with whatever selection of controls seems good, e.g. slider, textfield, number, and the framework collects all of these on one mod settings page, generates the UI and calls the SettingsChanged() callbacks when settings have been loaded or changed by the user. Reading the settings is easy since the SettingsHandle<T> will implicitly convert to to T.

**Comment by Skau** [comment]
This sounds interesting, and definitely would help consumers and modders have a more streamlined process for settings. The question is - should this be its own mod like HugsLib is?

**Comment by Tyler-IN** [comment]
Possibly. Can flesh it out here and fork it off.

**Comment by tynakuh** [comment]
This would be great for all the modders. +1

**Comment by Fumblesneeze** [comment]
I would just like to note that it would really be useful for acceptance if mods can add their own view/viewmodel to the settings framework. I imagine the main menu will have one "Mod Settings" button, and then there's a screen that has one expander per mod and in that expander there's either the supplied view *or* the auto-generated one.

![example](https://user-images.githubusercontent.com/25569137/78777322-9f6e8900-7999-11ea-9f2a-ac108ed489fc.png)
There is an example on how it looks in Rimworld using hugslib.

**Comment by tynakuh** [comment]
So Bannerlord Tweaks released 1.1.0 today which has a pretty sleek looking mod options menu

**Comment by mipen** [comment]
I've started the ball rolling on the mod settings page. Bannerlord Tweaks now contains a mod settings page that is very easy to hook into. At the moment it is pregenerated with only bool, int and float value options, but I have aims to make it fully customisable

**Comment by FlayaN** [comment]
@mipen 

Please make this into a separate mod, not a fan of a "catch all" mod. Looks good though :)

Would love to have a community mod options.

**Comment by Tyler-IN** [comment]
@mipen Are you going to create a separate library for it?

**Comment by Tyler-IN** [comment]
Linking https://github.com/mipen/BannerlordTweaks/issues/16

**Comment by Tyler-IN** [comment]
![image](https://user-images.githubusercontent.com/33945568/78963199-bfe73200-7ac4-11ea-86a4-febeb42fecc8.png)

**Comment by Tyler-IN** [comment]
This looks suspiciously similar: https://www.nexusmods.com/mountandblade2bannerlord/mods/504?tab=posts&BH=0

**Comment by tbeswick96** [comment]
Have any decisions been made between devs as to which mod settings library will be the main one going forward?
Personally I like the look of this one and it seems to operate better as you can edit it during game sessions, but it seems like it'd make more sense to have it as part of modlib?

**Comment by Aragas** [comment]
ModLib and MBOptionsScreen switched to MIT license
