### ISSUE TITLE
>10 Food Variety Does Not Give Appropriate Morale Bonus

### ISSUE THREAD

**Issue by Aresmar65** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#67]
Same as title. When you have oil in your inventory food morale is always +2 regardless of current inventory.

**Comment by Skau** [comment]
This one is pretty interesting. I looked up oil in spitems.xml and I can't find an ItemComponent element with a morale_bonus child element.  All foods usually has that, and it's used to calculate morale
Pictures explain better:
![Code_VkRsPpUlD8](https://user-images.githubusercontent.com/12700623/78785328-4574c000-79a7-11ea-97f2-ef98f6cbdf9a.png)
![Code_yMwmpLOsFX](https://user-images.githubusercontent.com/12700623/78785497-8967c500-79a7-11ea-81aa-747bc476aa96.png)
There might be a reason for this, and it might not be connected to the bug at all, but I thought I should mention it. Morale (at least in `DefaultPartyMoraleModel`) just checks food variety anyways.

**Comment by johnshepardn7117** [comment]
Its Oil or Wine combined with Dates. I just double checked it.

i.e:
If you have oil and wine is ok
If you have dates alone is fine.
But oil/wine combined with dates in the inventory trigger the lower morale. I don't know why.

**Comment by Skau** [comment]
Hm, I can't seem to reproduce it. Could you provide a save where it happens?

**Comment by DrMaple** [comment]
Here's a save where I have every food in the game, but no oil in my inventory. If you go to the city right next to me and buy the oil, the morale bonus drops from +8 to +2
[Oil Food Morale Bug.zip](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4454001/Oil.Food.Morale.Bug.zip)

**Comment by DrMaple** [comment]
It actually has nothing to do with oil specifically it looks like. It's just having all the food + oil. You can have all but one food and oil and still have the +8 bonus, but once you have all 11 items it goes back down to +2.

**Comment by zagganoth** [comment]
huh, figured out what's wrong, game has a switch statement with highest food variety being 10, any higher and it defaults to 2
![image](https://user-images.githubusercontent.com/25257995/78864063-bb047e80-79ef-11ea-9250-e78d850a1391.png)
