### ISSUE TITLE
XP Gain is Bugged

### ISSUE THREAD

**Issue by alike03** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#68]
tl;dr: Take a look at that image. https://imgur.com/a/RyKvYcU
0.83+10.67+92.5 = ...4? Well, no but 
0.83+0.67+2.5 DOES = 4

Here is the reddit tread with more info on the subject: https://www.reddit.com/r/mountandblade/comments/fw593a/the_extremely_bugged_math_behind_xp_gain_in/

**Comment by Skau** [comment]
Looking at the thread they seem to believe it's a visual bug. Still need to be looked more into though, visual bugs are still bugs.

**Comment by tynakuh** [comment]
It's a visual bug, the algorithm is:
20/10+level   *  0.4 * attribute * focus
(Then there's additional logic if you exceed the cap)

Worth fixing visual side though.

**Comment by TYoung86** [comment]
Fix and explanation of what is happening is in the PR

**Comment by Tyler-IN** [comment]
Fix and explanation of what is happening is in the PR

**Comment by Tyler-IN** [comment]
(Posted w/ wrong GH account, my bad)
