### ISSUE TITLE
e1.0.8 + 0.0.2 Crash on Siege

### ISSUE THREAD

**Issue by Sukha1337** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#85]
Removed all other mods, game hanging/crashing when trying to siege a Town...

[save.zip](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/files/4454951/save.zip)

**Comment by BoDDEneR** [comment]
Can agree with that, happened to me too, Originally i want to create a topic, but issue was reported already.

**Comment by tynakuh** [comment]
Thanks, Identified the issue, hotfix incoming.

**Comment by tynakuh** [comment]
Hotfix is released, could you verify it's resolved?

**Comment by Sukha1337** [comment]
Yes its fixed

**Comment by Sukha1337** [comment]
Fixed

**Comment by tynakuh** [comment]
Re-opening this for a bit of time for visibility/minimizing duplicates

**Comment by ExoLyzix** [comment]
Doesn't seem to crash for me either after playing a bit on the main campaign

**Comment by tynakuh** [comment]
Closing this ticket now.
