### ISSUE TITLE
Extra Arrows / Throwing Weapons perks not working

### ISSUE THREAD

**Issue by ExoLyzix** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#87]
Those perks aren't working : 

- Bow tree : Large Quiver, Battle Equipped

- Throwing : Fully Armed, Battle Ready, Well Prepared ( Not sure about that one )

- Riding : Spare Arrows, Spare Throwing Weapons

- Athletics : Extra Arrows, Extra Throwing Weapons

They're all supposed to give you a certain amount of arrows / throwing weapons but they don't, I didn't see any issues posted about it

**Comment by ajseavey** [comment]
I don't know if party members even have projectile limits enforced. I'll be taking a look at this in the near future.

**Comment by fnzr** [comment]
@ajseavey I've been looking into this, so if you haven't started working on it yet, I think I got it.

**Comment by ajseavey** [comment]
Which part? There are changes coming soon that may make this easier.

**Comment by fnzr** [comment]
I'm looking at bow first, but all of extra ammo perks should follow pretty much the same logic.
I'm using Harmony to patch `Agent::InitializeMissionEquipment`

**Comment by ajseavey** [comment]
Check the current master. Stuff related to Agent::WeaponEquipped just got merged that could also make this a lot simpler.

**Comment by fnzr** [comment]
Alright, I'll make sure to check it.

**Comment by fnzr** [comment]
This should be closed and then opened a issue exclusively for the Well Prepared perk in the Throwing tree.
