### ISSUE TITLE
Delayed loading, referencing other module's assemblies

### ISSUE THREAD

**Issue by Tyler-IN** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#9]
The BMTournamentXP mod released a version that had an assembly reference to the SandBox.dll assembly in the SandBox module.
So for BMTournamentXP, to use this feature and load properly, the SubModules.xml would be the following.

```xml
<?xml version="1.0" encoding="utf-8"?>
<Module>
  <Name value="Tournament XP"/>
  <Id value="BMTournamentXP"/>
  <Version value="e1.1.2"/>
  <SingleplayerModule value="true"/>
  <MultiplayerModule value="false"/>
  <Official value="false"/>
  <DependedModules>
    <DependedModule Id="Native"/>
    <DependedModule Id="SandBoxCore"/>
    <DependedModule Id="Sandbox"/>
    <DependedModule Id="CustomBattle"/>
    <DependedModule Id="StoryMode" />
    <DependedModule Id="CommunityPatch" />
  </DependedModules>
  <SubModules/>
  <DelayedSubModules>
    <SubModule>
      <Name value="BMTournamentXP"/>
      <DLLName value="BMTournamentXP.dll"/>
      <SubModuleClassType value="BMTournamentXP.BMTournamentXPMain"/>
      <Tags>
        <Tag key="DedicatedServerType" value="none" />
        <Tag key="IsNoRenderModeElement" value="false" />
      </Tags>
    </SubModule>
  </DelayedSubModules>
  <Xmls/>
</Module>
```

* The additions are `
    <DependedModule Id="CommunityPatch" />` and `<DelayedSubModules>` element.

**Comment by Dealman** [comment]
Out of curiosity, why is the `<DelayedSubModules>` element necessary here? I'm working on a mod similar to his - which also makes use of SandBox.dll.

But I haven't been nesting my SubModule under `<DelayedSubModules>`, has worked fine thus far from what I can tell. Thanks!

**Comment by Tyler-IN** [comment]
If you reference SandBox.dll and your mod is loaded by the TW submodule loader, it will enumerate types and come across the references you imported from SandBox.dll.
The SandBox.dll will not be loaded and the game will crash.

Delaying your module's loading will cause the mod to initialize after SandBox.dll is loaded and thus linkage will succeed when the types are processed.
