### ISSUE TITLE
Please use BannerLord Tweaks Mod Menu!

### ISSUE THREAD

**Issue by Jayshua83** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#97]
Bannerlord Tweaks uses a great mode menu and I think his code for it is open? maybe you can incorporate it in and make it the standard mod menu?

**Comment by Jayshua83** [comment]
I had issues with the Free Play mod pushing the mod Options button down!

**Comment by Tyler-IN** [comment]
https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/61

Only if it's spun off as a separate library.
